export default { id: 14, label: "L14", formula: "L = {w ∈ {a,b}* / |w|a = |w|b}", impossible: true,                                  desc: "",                                                                 shortestWord: '',         regex: /^[ab]*$/, validate: w => [...w].filter(c=>c==='a').length === [...w].filter(c=>c==='b').length, alphabet: ['a', 'b'], acceptedWords: [],  rejectedWords: ["a","b","aab"],         hint: "Cuidado, essa é clássica! Garantir quantidade igual pode exigir muitos estados.",                                   successMsg: "Sobreviveu à máquina de estados complexa!",
    tutorials: {
      onStart: { type: 'theory', title: 'Linguagem IMPOSSÍVEL para AFD!', dialog: [
        'Esta linguagem é IMPOSSÍVEL para qualquer AFD — impossibilidade provada matematicamente!',
        'Para aceitar a^k b^k, o AFD precisaria lembrar k enquanto lê os "b"s. Mas k é ilimitado!',
        'Com apenas N estados fixos, palavras longas forçam repetição de estado (Pigeonhole). O Lema do Bombeamento conclui: a^(N+j)b^N seria aceita — mas ela não está em L. Contradição!',
        'Conclusão: AFDs não têm memória para comparar dois contadores sem ordem fixa. Isso é coisa de PDA (pilha).',
        'Tente construir mesmo assim. Sentir os limites do AFD é a melhor aula de teoria!',
      ] },
    },
    boardWords: ['λ', 'ab / ba', 'bbaa', 'bbbaaa / bbbbaaaa...'],
    guidedLesson: [
      { text: 'Vamos tentar construir um AFD para <b>|w|a = |w|b</b> mesmo assim — e ver onde ele quebra.<br/>Começando pelo básico: <b>λ</b> (palavra vazia) tem 0 "a"s e 0 "b"s, então é aceita. q0 é inicial <u>e</u> final.',
        boardDoneUpTo: 0, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 1000, y: 1000, isInitial: true, isFinal: true },
          ],
          transitions: [] } },
      { text: 'Agora "ab" e "ba" também precisam ser aceitas. Cada uma pede um caminho próprio: q0→q1→qF (para "ab") e q0→q2→qF (para "ba").',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 1000, y: 1000, isInitial: true, isFinal: true },
            { id: 'q1', label: 'q1', x: 400,  y: 300,  isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 1600, y: 300,  isInitial: false, isFinal: false },
            { id: 'qF', label: 'qF', x: 1000, y: 1700, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'qF', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'qF', symbol: 'a' },
          ] } },
      { text: 'Mas e <b>"bbaa"</b>? 2 "b"s pendentes antes de qualquer "a" — q2 já leu 1 "b", mas o 2° "b" não tem pra onde ir! Preciso de q3 para "lembrar" 2 "b"s em aberto.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 1000, y: 200,  isInitial: true, isFinal: true },
            { id: 'q1', label: 'q1', x: 400,  y: 600,  isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 1600, y: 600,  isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 1600, y: 1150, isInitial: false, isFinal: false },
            { id: 'qF', label: 'qF', x: 1000, y: 1700, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'qF', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'qF', symbol: 'a' },
            { from: 'q2', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q2', symbol: 'a' },
          ] } },
      { text: 'Só que "bbbaaa" tem 3 "b"s pendentes — pede q4. "bbbbaaaa" tem 4 — pede q5. <u>Sempre</u> mais um estado para cada "b" extra antes do primeiro "a".',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 1000, y: 100,  isInitial: true, isFinal: true },
            { id: 'q1', label: 'q1', x: 300,  y: 450,  isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 1700, y: 450,  isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 1700, y: 950,  isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 1700, y: 1450, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 1700, y: 1950, isInitial: false, isFinal: false },
            { id: 'qF', label: 'qF', x: 900,  y: 1450, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'qF', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'qF', symbol: 'a' },
            { from: 'q2', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q2', symbol: 'a' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q3', symbol: 'a' },
            { from: 'q4', to: 'q5', symbol: 'b' },
            { from: 'q5', to: 'q4', symbol: 'a' },
          ] } },
      { text: '<b>É isso.</b> Não tem limite: pra <u>qualquer</u> número N de estados, dá pra achar uma palavra com N+1 "b"s pendentes que quebra o autômato. Em AFD isso fica infinito, porque <b>AFD não tem memória</b> — só estados fixos, não existe "contador" que cresça à vontade.<br/>Esse exercício só é resolvível com <b>AP</b> (autômato com pilha) — a pilha guarda a diferença entre as contagens de "a" e "b", sem limite. A gente resolve ele lá! 🔜',
        boardDoneUpTo: 4, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 1000, y: 100,  isInitial: true, isFinal: true },
            { id: 'q1', label: 'q1', x: 300,  y: 450,  isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 1700, y: 450,  isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 1700, y: 950,  isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 1700, y: 1450, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 1700, y: 1950, isInitial: false, isFinal: false },
            { id: 'qF', label: 'qF', x: 900,  y: 1450, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'qF', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'qF', symbol: 'a' },
            { from: 'q2', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q2', symbol: 'a' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q3', symbol: 'a' },
            { from: 'q4', to: 'q5', symbol: 'b' },
            { from: 'q5', to: 'q4', symbol: 'a' },
          ] } },
    ] };
