// L46 — grafo extraído de L45.xml por migrador_afd.js
export default {
  nodes: [
  { id: 'q0', x: 53, y: 202, isInitial: true, isFinal: false },
  { id: 'q1', x: 121, y: 201, isInitial: false, isFinal: false },
  { id: 'q2', x: 195, y: 200, isInitial: false, isFinal: false },
  { id: 'q3', x: 266, y: 198, isInitial: false, isFinal: false },
  { id: 'q4', x: 342, y: 200, isInitial: false, isFinal: false },
  { id: 'q5', x: 405, y: 108, isInitial: false, isFinal: false },
  { id: 'q6', x: 528, y: 110, isInitial: false, isFinal: false },
  { id: 'q7', x: 628, y: 155, isInitial: false, isFinal: false },
  { id: 'q8', x: 726, y: 183, isInitial: false, isFinal: false },
  { id: 'q9', x: 942, y: 385, isInitial: false, isFinal: false },
  { id: 'q10', x: 622, y: 309, isInitial: false, isFinal: false },
  { id: 'q11', x: 350, y: 334, isInitial: false, isFinal: false },
  { id: 'q12', x: 83, y: 396, isInitial: false, isFinal: true }
],
  transitions: [
  { from: 'q5', to: 'q4', symbol: 'a, b, d' },
  { from: 'q3', to: 'q4', symbol: 'd' },
  { from: 'q4', to: 'q5', symbol: 'c' },
  { from: 'q6', to: 'q7', symbol: 'c' },
  { from: 'q7', to: 'q8', symbol: 'c' },
  { from: 'q10', to: 'q8', symbol: 'a, c' },
  { from: 'q0', to: 'q1', symbol: 'a' },
  { from: 'q8', to: 'q9', symbol: 'd' },
  { from: 'q1', to: 'q2', symbol: 'b' },
  { from: 'q12', to: 'q9', symbol: 'd' },
  { from: 'q6', to: 'q4', symbol: 'a, b, d' },
  { from: 'q9', to: 'q8', symbol: 'a, b' },
  { from: 'q11', to: 'q8', symbol: 'b, c' },
  { from: 'q11', to: 'q12', symbol: 'a' },
  { from: 'q12', to: 'q8', symbol: 'a, b, c' },
  { from: 'q4', to: 'q4', symbol: 'a, b, d' },
  { from: 'q8', to: 'q8', symbol: 'a, b, c' },
  { from: 'q2', to: 'q3', symbol: 'c' },
  { from: 'q9', to: 'q9', symbol: 'd' },
  { from: 'q11', to: 'q9', symbol: 'd' },
  { from: 'q7', to: 'q4', symbol: 'a, b, d' },
  { from: 'q10', to: 'q11', symbol: 'b' },
  { from: 'q5', to: 'q6', symbol: 'c' },
  { from: 'q9', to: 'q10', symbol: 'c' },
  { from: 'q10', to: 'q9', symbol: 'd' }
],
};
