export const lote3 = [
  { id: 41, label: "L40", formula: "L = { a^n b^2m d c^3p d | n, m, p ≥ 0 }",                          desc: "",                                                                 shortestWord: "dd",       regex: /^a*(bb)*d(ccc)*d$/,                                         alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["dd","abbdd","adcccdd"],  rejectedWords: ["d","abd","abcdd"],     hint: "Essa é grande! Blocos de 'b' em duplas, o primeiro 'd' serve de ponte, e 'c' em trios.",                            successMsg: "Sintaxe complexa analisada com sucesso.",
    tutorials: {
      onStart: { type: 'theory', title: 'Blocos: a-block, b-pares, d, c-trios, d!', dialog: [
        'L40: a^n b^2m d c^3p d. a-s, depois b-pares, depois d, depois c-trios, depois d.',
        '"dd" ✓ (0a 0b 0c). "abbdd" ✓ (1a 1par-b). "adcccd" ✓ (1a 1trio-c).',
        '6 estados: q0(ini), q1(b-impar), q2(apos-d), q3(c-1), q4(c-2), q5(f).',
      ] },
      onDrawGraph: { type: 'mechanic', title: '6 Estados em Sequencia', dialog: [
        'q0 loop a. q0—b→q1—b→q0 (pares). q0—d→q2 (ponte).',
        'q2—d→q5(f). q2—c→q3—c→q4—c→q2 (trio completo volta a q2).',
        '"adcccd": q0—a→q0—d→q2—c→q3—c→q4—c→q2—d→q5(f) ✓.',
      ] },
    },
    boardWords: ['dd', 'abbdd', 'adcccd'],
    guidedLesson: [
      { text: 'Blocos sequenciais: a* — b-pares — d — c-trios — d!<br/>Aceitar: <b>dd</b>, <b>abbdd</b>, <b>adcccd</b>. Rejeitar: d, abd, abcdd.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Spotlight <b>dd</b>: núcleo q0→q2(d)→q5(final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Fix: q0→q2(d)→q5(final). "dd"✓. Próxima: "abbdd"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Spotlight <b>abbdd</b>: q0 lê "a" e "b" — sem seta! Preciso de loop a e q1 para b-pares.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Fix: q0 loop a, q0→q1(b)→q0(b). "abbdd"✓. Próxima: "adcccd"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 10, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Spotlight <b>adcccd</b>: q2 lê "c" — sem seta! Preciso de ciclo de c-trios.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 10, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Fix: q2→q3(c)→q4(c)→q2(c). "adcccd"✓ Concluído!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 10, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 48, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 40, y: 70, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 70, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'c' },
            { from: 'q4', to: 'q2', symbol: 'c' },
          ] } },
    ] },
  { id: 42, label: "L41", formula: "L = { a(dcb)^n a^m (bb)^p | n > 0, m > 0, p ≥ 0 }",               desc: "",                                                                 shortestWord: "adcba",    regex: /^a(dcb)+a+(bb)*$/,                                          alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["adcba","adcbaa","adcbabb"], rejectedWords: ["a","adcb","dcba"],  hint: "Siga a receita passo a passo, o ciclo 'dcb' é o coração do automato.",                                              successMsg: "Ciclo gigante dominado.",
    tutorials: {
      onStart: { type: 'theory', title: 'Ciclo dcb: a + dcb+ + a+ + b-pares!', dialog: [
        'L41: "a", depois 1+ ciclos de "dcb", depois 1+ "a", depois b-pares opcionais.',
        '"adcba" ✓ (1 ciclo, 1a). "adcbaa" ✓ (1 ciclo, 2a). "adcbabb" ✓ (1a, 1par-b).',
        '"a" ✗ (sem dcb). "adcb" ✗ (sem a final). 7 estados em cadeia.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '7 Estados: Cadeia + Ciclo + b-pares', dialog: [
        'q0—a→q1—d→q2—c→q3—b→q4 (ciclo dcb). q4—d→q2 (repetir ciclo).',
        'q4—a→q5(f). q5 loop a. q5—b→q6—b→q5 (pares de b).',
        '"adcbabb": q0→q1→q2→q3→q4→q5—b→q6—b→q5(f) ✓.',
      ] },
    },
    boardWords: ['adcba', 'adcbaa', 'adcbabb'],
    guidedLesson: [
      { text: 'Ciclo dcb! a + (dcb)+ + a+ + (bb)*<br/>Aceitar: <b>adcba</b>, <b>adcbaa</b>, <b>adcbabb</b>. Rejeitar: a, adcb, dcba.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Spotlight <b>adcba</b>: cadeia q0→q1(a)→q2(d)→q3(c)→q4(b) + ciclo q4→q2(d) e saída q4→q5(final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Fix: cadeia + ciclo. "adcba"✓. Próxima: "adcbaa"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 24, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 40, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 56, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 72, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q2', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'a' },
          ] } },
      { text: 'Spotlight <b>adcbaa</b>: q5 lê segundo "a" — sem loop! Preciso de q5→q5(a).',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 24, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 40, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 56, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 72, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q2', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'a' },
          ] } },
      { text: 'Fix: q5 loop a. "adcbaa"✓. Próxima: "adcbabb"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 24, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 40, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 56, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 72, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q2', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'a' },
            { from: 'q5', to: 'q5', symbol: 'a' },
          ] } },
      { text: 'Spotlight <b>adcbabb</b>: q5 lê "b" — sem seta! Preciso de q6 para b-pares.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 24, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 40, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 56, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 72, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q2', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'a' },
            { from: 'q5', to: 'q5', symbol: 'a' },
          ] } },
      { text: 'Fix: q5→q6(b)→q5(b). "adcbabb"✓ Concluído!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 24, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 40, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 56, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 72, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
            { id: 'q6', label: 'q6', x: 88, y: 70, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q2', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'a' },
            { from: 'q5', to: 'q5', symbol: 'a' },
            { from: 'q5', to: 'q6', symbol: 'b' },
            { from: 'q6', to: 'q5', symbol: 'b' },
          ] } },
    ] },
  { id: 43, label: "L42", formula: "L = { a^n b^2m c c d^p | n > 0 (ímpar), m, p ≥ 0 }",              desc: "",                                                                 shortestWord: "acc",      regex: /^a(aa)*(bb)*ccd*$/,                                         alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["acc","aaacc","accdd"],   rejectedWords: ["cc","aacc","abcc"],    hint: "O início exige vai-e-volta ímpar para os 'a's, depois 'b's em duplas.",                                             successMsg: "Paridade e duplas em sequência perfeita.",
    tutorials: {
      onStart: { type: 'theory', title: 'a-ímpar + b-pares + cc + d*!', dialog: [
        'L42: a^n b^2m cc d^p onde n > 0 ímpar, m ≥ 0, p ≥ 0.',
        '"acc" ✓ (1a, 0b). "aaacc" ✓ (3a, 0b). "abbcc" ✓ (1a, 2b). "aacc" ✗ (2a = par!).',
        '6 estados: q0 (start), q1 (odd-a), q2 (even-a), q3 (odd-b), q4 (1ºc), q5 (final).',
      ] },
      onDrawGraph: { type: 'mechanic', title: '6 Estados: Paridade + Cadeia', dialog: [
        'q0—a→q1↔q2(a). q1 = a-ímpar (válido). q2 = a-par (precisa de mais um "a").',
        'q1—c→q4—c→q5(f). q5 loop d. "cc" obrigatório antes dos d\'s.',
        'q1—b→q3—b→q1. Pares de "b" retornam a q1. Ímpar de "b" trava em q3.',
      ] },
    },
    boardWords: ['acc', 'aaacc', 'abbcc', 'accdd'],
    guidedLesson: [
      { text: 'a-ímpar + b-pares + cc + d*!<br/>Aceitar: <b>acc</b>, <b>aaacc</b>, <b>abbcc</b>, <b>accdd</b>. Rejeitar: cc, aacc, abcc.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Spotlight <b>acc</b> e <b>aaacc</b>: ambas precisam de paridade-a (q1↔q2) + cadeia cc.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Fix: q0→q1↔q2(a), q1→q4(c)→q5(final,loop d). "acc"✓ "aaacc"✓. Próximas: "abbcc" e "accdd"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 48, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 68, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q4', symbol: 'c' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Spotlight <b>abbcc</b> e <b>accdd</b>: "abbcc" — q1 sem seta para "b"! Preciso de q3 para b-pares.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 48, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 68, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q4', symbol: 'c' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Fix: +q3, q1→q3(b)→q1(b). "abbcc"✓ "accdd"✓ Concluído!',
        boardDoneUpTo: 4, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 48, y: 35, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 28, y: 70, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 68, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q4', symbol: 'c' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q5', symbol: 'd' },
          ] } },
    ] },
  { id: 44, label: "L43", formula: "L = { w ∈ {a,b,c,d}* | subpalavra 'ab' e sufixo 'cd' }",           desc: "",                                                                 shortestWord: "abcd",     regex: /^[abcd]*ab[abcd]*cd$/,                                      alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["abcd","aabcd","abccd"],  rejectedWords: ["λ","acd","abdc"],      hint: "Ache primeiro o 'ab'. Depois de achar, fique aguardando um 'cd' para finalizar.",                                   successMsg: "Subpalavra + Sufixo resolvido.",
    tutorials: {
      onStart: { type: 'theory', title: 'Subpalavra "ab" + Sufixo "cd"!', dialog: [
        'L43: a palavra deve conter "ab" em algum lugar E terminar com "cd".',
        '"abcd" ✓ (ab subpalavra, cd sufixo). "aabcd" ✓. "abccd" ✓.',
        '"acd" ✗ (sem "ab"). "abdc" ✗ ("ab" ok mas não termina em "cd").',
      ] },
      onDrawGraph: { type: 'mechanic', title: '5 Estados: Detectar + Esperar', dialog: [
        'q0→q1(a): buscando "ab". q1→q2(b): "ab" encontrado! q0 e q1 voltam com c,d.',
        'q2→q3(c): primeiro "c" do sufixo. q3→q4(d): "cd" completo — final!',
        'q2 e q4 loop em a,b,d. q3 loop em c. Mismatches em q0,q1 voltam ao início.',
      ] },
    },
    boardWords: ['abcd', 'aabcd', 'abccd'],
    guidedLesson: [
      { text: 'Subpalavra "ab" e sufixo "cd"!<br/>Aceitar: <b>abcd</b>, <b>aabcd</b>, <b>abccd</b>. Rejeitar: λ, acd, abdc.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Spotlight <b>abcd</b>: cadeia simples q0→q1(a)→q2(b)→q3(c)→q4(final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Fix: cadeia q0→q1(a)→q2(b)→q3(c)→q4(final,d). "abcd"✓. Próximas: "aabcd" e "abccd"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 50, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
          ] } },
      { text: 'Spotlight <b>aabcd</b> e <b>abccd</b>: "aabcd" — q1 sem loop a! "abccd" — q3 sem loop c! Preciso de loops e retornos.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 50, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
          ] } },
      { text: 'Fix loops/retornos: q0 loop b,c,d; q1 loop a, q1→q0(c,d); q2 loop a,b,d; q3 loop c; q4→q3(c), q4→q2(a,b,d). "aabcd"✓ "abccd"✓ Concluído!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 50, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'b,c,d' },
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'c,d' },
            { from: 'q2', to: 'q2', symbol: 'a,b,d' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q2', symbol: 'a,b' },
            { from: 'q3', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
            { from: 'q4', to: 'q2', symbol: 'a,b,d' },
            { from: 'q4', to: 'q3', symbol: 'c' },
          ] } },
    ] },
  { id: 45, label: "L44", formula: "L = { w ∈ {a,b,c,d}* | prefixo 'abcd' e sufixo 'dcba' }",          desc: "",                                                                 shortestWord: "abcddcba", regex: /^abcd[abcd]*dcba$/,                                         alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["abcddcba","abcdadcba"],  rejectedWords: ["abcd","dcba","abcdcd"], hint: "Sanduíche de palavras! O começo e o fim são engessados.",                                                           successMsg: "Sanduíche de letras perfeito.",
    tutorials: {
      onStart: { type: 'theory', title: 'Prefixo "abcd" E sufixo "dcba"!', dialog: [
        'L44: comecar com "abcd" obrigatorio, terminar com "dcba" obrigatorio.',
        '"abcddcba" ✓ (min, sobreposicao). "abcdadcba" ✓ (1a no meio).',
        '"abcd" ✗ (falta sufixo). "dcba" ✗ (falta prefixo). 9 estados.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '9 Estados: Prefixo + Sufixo', dialog: [
        'Prefixo: q0—a→q1—b→q2—c→q3—d→q4. Sufixo: q4—d→q5—c→q6—b→q7—a→q8(f).',
        'q4 loop a,b,c. q5 loop d; q5—a,b→q4. q6—a,c→q4; q6—d→q5.',
        'q7—b,c→q4; q7—d→q5. q8—a,b,c→q4; q8—d→q5.',
      ] },
    },
    boardWords: ['abcddcba', 'abcdadcba'],
    guidedLesson: [
      { text: 'Sanduiche: prefixo "abcd" obrigatorio + sufixo "dcba" obrigatorio!<br/>Aceitar: <b>abcddcba</b>, <b>abcdadcba</b>. Rejeitar: abcd, dcba.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Spotlight <b>abcddcba</b>: dois prefixos e sufixos em cadeia linear de 9 estados.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Fix: cadeia q0→…→q4(d)→q5(d)→q6(c)→q7(b)→q8(final,a). "abcddcba"✓. Próxima: "abcdadcba"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 21, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 34, y: 35, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 47, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 60, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 73, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 86, y: 35, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 86, y: 65, isInitial: false, isFinal: false },
            { id: 'q8', label: 'q8', x: 73, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'd' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q7', symbol: 'b' },
            { from: 'q7', to: 'q8', symbol: 'a' },
          ] } },
      { text: 'Spotlight <b>abcdadcba</b>: q4 lê "a" — sem loop! Preciso de loops e retornos em q4 e sufixo.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 21, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 34, y: 35, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 47, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 60, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 73, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 86, y: 35, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 86, y: 65, isInitial: false, isFinal: false },
            { id: 'q8', label: 'q8', x: 73, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'd' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q7', symbol: 'b' },
            { from: 'q7', to: 'q8', symbol: 'a' },
          ] } },
      { text: 'Fix loops/retornos: q4 loop a,b,c; q5 loop d, q5→q4(a,b); q6→q5(d), q6→q4(a,c); q7→q4(b,c); q8→q4(a,b,c). "abcdadcba"✓ Concluído!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 21, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 34, y: 35, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 47, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 60, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 73, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 86, y: 35, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 86, y: 65, isInitial: false, isFinal: false },
            { id: 'q8', label: 'q8', x: 73, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
            { from: 'q4', to: 'q4', symbol: 'a,b,c' },
            { from: 'q4', to: 'q5', symbol: 'd' },
            { from: 'q5', to: 'q4', symbol: 'a,b' },
            { from: 'q5', to: 'q5', symbol: 'd' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q4', symbol: 'a,c' },
            { from: 'q6', to: 'q5', symbol: 'd' },
            { from: 'q6', to: 'q7', symbol: 'b' },
            { from: 'q7', to: 'q4', symbol: 'b,c' },
            { from: 'q7', to: 'q5', symbol: 'd' },
            { from: 'q7', to: 'q8', symbol: 'a' },
            { from: 'q8', to: 'q4', symbol: 'a,b,c' },
            { from: 'q8', to: 'q5', symbol: 'd' },
          ] } },
    ] },
  { id: 46, label: "L45", formula: "L = { w ∈ {a,b,c,d}* | pref 'abcd', sub 'cccc', suf 'dcba' }",    desc: "",                                                                 shortestWord: "abcdccccdcba", regex: /^abcd[abcd]*cccc[abcd]*dcba$/,                          alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["abcdccccdcba","abcdaccccdcba"], rejectedWords: ["abcddcba","abcdcccdcba","dcba"], hint: "Faça o caminho em três estágios lógicos na sua cabeça.",                                          successMsg: "Você construiu um autômato enorme, meus parabéns!",
    tutorials: {
      onStart: { type: 'theory', title: 'Prefixo abcd + 4c seguidos + sufixo dcba!', dialog: [
        'L45: comecar com "abcd", conter "cccc" em algum lugar, terminar com "dcba".',
        '"abcdccccdcba" ✓ (min). "abcdaccccdcba" ✓ (a no meio). 13 estados!',
        'Tres fases: prefixo fixo → detectar cccc → sufixo fixo.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '13 Estados: Tres Fases', dialog: [
        'Prefixo: q0—a→q1—b→q2—c→q3—d→q4. q4 loop a,b,d; q4—c→q5.',
        'cccc: q5—c→q6—c→q7—c→q8. Mismatch volta a q4. q8 loop a,b,c.',
        'Sufixo: q8—d→q9—c→q10—b→q11—a→q12(f). Mismatches → q8 ou q9.',
      ] },
    },
    boardWords: ['abcdccccdcba', 'abcdaccccdcba'],
    guidedLesson: [
      { text: 'Tres fases: prefixo "abcd" + subpalavra "cccc" + sufixo "dcba"!<br/>Aceitar: <b>abcdccccdcba</b>, <b>abcdaccccdcba</b>. Rejeitar: abcddcba, abcdcccdcba.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Spotlight <b>abcdccccdcba</b>: cadeia linear de 13 estados — prefixo + 4c + sufixo.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Fix: cadeia q0→…→q4(c)→q5(c)→q6(c)→q7(c)→q8(d)→q9(c)→q10(b)→q11(a)→q12(final). "abcdccccdcba"✓. Próxima: "abcdaccccdcba"!',
        boardDoneUpTo: 1,
        stateUpdate: {
          nodes: [
            { id: 'q0',  label: 'q0',  x:  6, y: 28, isInitial: true,  isFinal: false },
            { id: 'q1',  label: 'q1',  x: 14, y: 28, isInitial: false, isFinal: false },
            { id: 'q2',  label: 'q2',  x: 22, y: 28, isInitial: false, isFinal: false },
            { id: 'q3',  label: 'q3',  x: 30, y: 28, isInitial: false, isFinal: false },
            { id: 'q4',  label: 'q4',  x: 38, y: 28, isInitial: false, isFinal: false },
            { id: 'q5',  label: 'q5',  x: 47, y: 28, isInitial: false, isFinal: false },
            { id: 'q6',  label: 'q6',  x: 56, y: 28, isInitial: false, isFinal: false },
            { id: 'q7',  label: 'q7',  x: 65, y: 28, isInitial: false, isFinal: false },
            { id: 'q8',  label: 'q8',  x: 74, y: 28, isInitial: false, isFinal: false },
            { id: 'q9',  label: 'q9',  x: 74, y: 68, isInitial: false, isFinal: false },
            { id: 'q10', label: 'q10', x: 65, y: 68, isInitial: false, isFinal: false },
            { id: 'q11', label: 'q11', x: 56, y: 68, isInitial: false, isFinal: false },
            { id: 'q12', label: 'q12', x: 47, y: 68, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0',  to: 'q1',  symbol: 'a' },
            { from: 'q1',  to: 'q2',  symbol: 'b' },
            { from: 'q2',  to: 'q3',  symbol: 'c' },
            { from: 'q3',  to: 'q4',  symbol: 'd' },
            { from: 'q4',  to: 'q5',  symbol: 'c' },
            { from: 'q5',  to: 'q6',  symbol: 'c' },
            { from: 'q6',  to: 'q7',  symbol: 'c' },
            { from: 'q7',  to: 'q8',  symbol: 'c' },
            { from: 'q8',  to: 'q9',  symbol: 'd' },
            { from: 'q9',  to: 'q10', symbol: 'c' },
            { from: 'q10', to: 'q11', symbol: 'b' },
            { from: 'q11', to: 'q12', symbol: 'a' },
          ],
        } },
      { text: 'Spotlight <b>abcdaccccdcba</b>: q4 lê "a" — sem loop! Preciso de loops e mismatches em q4 e fases cccc/sufixo.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0',  label: 'q0',  x:  6, y: 28, isInitial: true,  isFinal: false },
            { id: 'q1',  label: 'q1',  x: 14, y: 28, isInitial: false, isFinal: false },
            { id: 'q2',  label: 'q2',  x: 22, y: 28, isInitial: false, isFinal: false },
            { id: 'q3',  label: 'q3',  x: 30, y: 28, isInitial: false, isFinal: false },
            { id: 'q4',  label: 'q4',  x: 38, y: 28, isInitial: false, isFinal: false },
            { id: 'q5',  label: 'q5',  x: 47, y: 28, isInitial: false, isFinal: false },
            { id: 'q6',  label: 'q6',  x: 56, y: 28, isInitial: false, isFinal: false },
            { id: 'q7',  label: 'q7',  x: 65, y: 28, isInitial: false, isFinal: false },
            { id: 'q8',  label: 'q8',  x: 74, y: 28, isInitial: false, isFinal: false },
            { id: 'q9',  label: 'q9',  x: 74, y: 68, isInitial: false, isFinal: false },
            { id: 'q10', label: 'q10', x: 65, y: 68, isInitial: false, isFinal: false },
            { id: 'q11', label: 'q11', x: 56, y: 68, isInitial: false, isFinal: false },
            { id: 'q12', label: 'q12', x: 47, y: 68, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0',  to: 'q1',  symbol: 'a' },
            { from: 'q1',  to: 'q2',  symbol: 'b' },
            { from: 'q2',  to: 'q3',  symbol: 'c' },
            { from: 'q3',  to: 'q4',  symbol: 'd' },
            { from: 'q4',  to: 'q5',  symbol: 'c' },
            { from: 'q5',  to: 'q6',  symbol: 'c' },
            { from: 'q6',  to: 'q7',  symbol: 'c' },
            { from: 'q7',  to: 'q8',  symbol: 'c' },
            { from: 'q8',  to: 'q9',  symbol: 'd' },
            { from: 'q9',  to: 'q10', symbol: 'c' },
            { from: 'q10', to: 'q11', symbol: 'b' },
            { from: 'q11', to: 'q12', symbol: 'a' },
          ] } },
      { text: 'Fix loops/mismatches: q4 loop a,b,d; q5-q7 mismatch→q4; q8 loop a,b,c; q9 loop d, q9→q8(a,b); sufixo mismatches→q8. "abcdaccccdcba"✓ Concluído!',
        boardDoneUpTo: 2,
        stateUpdate: {
          nodes: [
            { id: 'q0',  label: 'q0',  x:  6, y: 28, isInitial: true,  isFinal: false },
            { id: 'q1',  label: 'q1',  x: 14, y: 28, isInitial: false, isFinal: false },
            { id: 'q2',  label: 'q2',  x: 22, y: 28, isInitial: false, isFinal: false },
            { id: 'q3',  label: 'q3',  x: 30, y: 28, isInitial: false, isFinal: false },
            { id: 'q4',  label: 'q4',  x: 38, y: 28, isInitial: false, isFinal: false },
            { id: 'q5',  label: 'q5',  x: 47, y: 28, isInitial: false, isFinal: false },
            { id: 'q6',  label: 'q6',  x: 56, y: 28, isInitial: false, isFinal: false },
            { id: 'q7',  label: 'q7',  x: 65, y: 28, isInitial: false, isFinal: false },
            { id: 'q8',  label: 'q8',  x: 74, y: 28, isInitial: false, isFinal: false },
            { id: 'q9',  label: 'q9',  x: 74, y: 68, isInitial: false, isFinal: false },
            { id: 'q10', label: 'q10', x: 65, y: 68, isInitial: false, isFinal: false },
            { id: 'q11', label: 'q11', x: 56, y: 68, isInitial: false, isFinal: false },
            { id: 'q12', label: 'q12', x: 47, y: 68, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0',  to: 'q1',  symbol: 'a' },
            { from: 'q1',  to: 'q2',  symbol: 'b' },
            { from: 'q2',  to: 'q3',  symbol: 'c' },
            { from: 'q3',  to: 'q4',  symbol: 'd' },
            { from: 'q4',  to: 'q4',  symbol: 'a,b,d' },
            { from: 'q4',  to: 'q5',  symbol: 'c' },
            { from: 'q5',  to: 'q4',  symbol: 'a,b,d' },
            { from: 'q5',  to: 'q6',  symbol: 'c' },
            { from: 'q6',  to: 'q4',  symbol: 'a,b,d' },
            { from: 'q6',  to: 'q7',  symbol: 'c' },
            { from: 'q7',  to: 'q4',  symbol: 'a,b,d' },
            { from: 'q7',  to: 'q8',  symbol: 'c' },
            { from: 'q8',  to: 'q8',  symbol: 'a,b,c' },
            { from: 'q8',  to: 'q9',  symbol: 'd' },
            { from: 'q9',  to: 'q8',  symbol: 'a,b' },
            { from: 'q9',  to: 'q9',  symbol: 'd' },
            { from: 'q9',  to: 'q10', symbol: 'c' },
            { from: 'q10', to: 'q8',  symbol: 'a,c' },
            { from: 'q10', to: 'q9',  symbol: 'd' },
            { from: 'q10', to: 'q11', symbol: 'b' },
            { from: 'q11', to: 'q8',  symbol: 'b,c' },
            { from: 'q11', to: 'q9',  symbol: 'd' },
            { from: 'q11', to: 'q12', symbol: 'a' },
            { from: 'q12', to: 'q8',  symbol: 'a,b,c' },
            { from: 'q12', to: 'q9',  symbol: 'd' },
          ],
        } },
    ] },
  { id: 47, label: "L46", formula: "L = { (a+b+c)* | qtd de a, b e c é par }",                          desc: "",                                                                 shortestWord: "",         regex: /^.*$/, validate: w => ['a','b','c'].every(c => [...w].filter(x=>x===c).length%2===0), alphabet: ['a', 'b', 'c'],        acceptedWords: ["λ","aabb","aabbcc"],      rejectedWords: ["a","b","abc"],         hint: "Isso é um cubo mágico de estados! Paridade para 3 letras exige 8 estados.",                                        successMsg: "Paridade em 3D completada!",
    tutorials: {
      onStart: { type: 'theory', title: 'Cubo de paridade: 3 letras, 8 estados!', dialog: [
        'L46: contar a, b e c separadamente. Aceito quando TODOS pares.',
        '"λ" ✓ (0+0+0). "aabb" ✓ (2a,2b,0c). "aabbcc" ✓ (2a,2b,2c). "a" ✗ (1a impar).',
        '8 combinacoes de paridade: 2^3 = 8 estados. Apenas q0(ini,f) aceita.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '8 Estados em Cubo', dialog: [
        'Linhas "a" (vertical): q0↔q1, q2↔q4, q3↔q5, q6↔q7.',
        'Linhas "b" (horizontal): q0↔q2, q1↔q4, q3↔q6, q5↔q7.',
        'Linhas "c" (cruzadas): q0↔q3, q1↔q5, q2↔q6, q4↔q7.',
      ] },
    },
    boardWords: ['λ', 'aabb', 'aabbcc'],
    guidedLesson: [
      { text: 'Cubo de paridade: a, b e c todos pares!<br/>Aceitar: <b>λ</b>, <b>aabb</b>, <b>aabbcc</b>. Rejeitar: a, b, abc.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Spotlight <b>λ</b>: palavra vazia — q0 inicial e final é suficiente.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Fix: q0(ini,final). λ✓. Próxima: "aabb"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [ { id: 'q0', label: 'q0', x: 50, y: 50, isInitial: true, isFinal: true } ],
          transitions: [] } },
      { text: 'Spotlight <b>aabb</b>: q0 lê "a" — sem seta! Preciso de raias a, b, c bidirecionais.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [ { id: 'q0', label: 'q0', x: 50, y: 50, isInitial: true, isFinal: true } ],
          transitions: [] } },
      { text: 'Fix: q0↔q1(a), q0↔q2(b), q0↔q3(c). "aabb"✓. Próxima: "aabbcc"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 12, y: 25, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 12, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 37, y: 25, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 62, y: 25, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' }, { from: 'q1', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q2', symbol: 'b' }, { from: 'q2', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q3', symbol: 'c' }, { from: 'q3', to: 'q0', symbol: 'c' },
          ] } },
      { text: 'Spotlight <b>aabbcc</b>: q1 e q2 sem seta "c"! Preciso dos 4 estados restantes do cubo.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 12, y: 25, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 12, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 37, y: 25, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 62, y: 25, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' }, { from: 'q1', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q2', symbol: 'b' }, { from: 'q2', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q3', symbol: 'c' }, { from: 'q3', to: 'q0', symbol: 'c' },
          ] } },
      { text: 'Fix: cubo completo +q4,q5,q6,q7. "aabbcc"✓ Concluído!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 12, y: 25, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 12, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 37, y: 25, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 62, y: 25, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 37, y: 70, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 62, y: 70, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 87, y: 25, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 87, y: 70, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' }, { from: 'q1', to: 'q0', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'a' }, { from: 'q4', to: 'q2', symbol: 'a' },
            { from: 'q3', to: 'q5', symbol: 'a' }, { from: 'q5', to: 'q3', symbol: 'a' },
            { from: 'q6', to: 'q7', symbol: 'a' }, { from: 'q7', to: 'q6', symbol: 'a' },
            { from: 'q0', to: 'q2', symbol: 'b' }, { from: 'q2', to: 'q0', symbol: 'b' },
            { from: 'q1', to: 'q4', symbol: 'b' }, { from: 'q4', to: 'q1', symbol: 'b' },
            { from: 'q3', to: 'q6', symbol: 'b' }, { from: 'q6', to: 'q3', symbol: 'b' },
            { from: 'q5', to: 'q7', symbol: 'b' }, { from: 'q7', to: 'q5', symbol: 'b' },
            { from: 'q0', to: 'q3', symbol: 'c' }, { from: 'q3', to: 'q0', symbol: 'c' },
            { from: 'q1', to: 'q5', symbol: 'c' }, { from: 'q5', to: 'q1', symbol: 'c' },
            { from: 'q2', to: 'q6', symbol: 'c' }, { from: 'q6', to: 'q2', symbol: 'c' },
            { from: 'q4', to: 'q7', symbol: 'c' }, { from: 'q7', to: 'q4', symbol: 'c' },
          ] } },
    ] },
  { id: 48, label: "L47", formula: "L = { a^n b^2m d c^3p d | n, m, p ≥ 0 }",                          desc: "(Revisão L40)",                                                    shortestWord: "dd",       regex: /^a*(bb)*d(ccc)*d$/,                                         alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["dd","abbdd","adcccdd"],  rejectedWords: ["d","abd","abcdd"],     hint: "Se chegou até aqui, já sabe: separe o problema em bloquinhos lógicos.",                                             successMsg: "Revisão bem sucedida.",
    tutorials: {
      onStart: { type: 'theory', title: 'Revisão L40: blocos a, b-pares, d, c-trios, d!', dialog: [
        'L47 e revisão de L40. Mesma linguagem a^n b^2m d c^3p d.',
        '"dd" ✓. "abbdd" ✓. "adcccd" ✓. "d" ✗. "abcdd" ✗.',
        'Relembre os 6 estados: q0(ini), q1(b-impar), q2(apos-d), q3(c-1), q4(c-2), q5(f).',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Revisao: 6 Estados', dialog: [
        'q0 loop a; q0—b→q1—b→q0; q0—d→q2.',
        'q2—d→q5(f); q2—c→q3—c→q4—c→q2.',
        'Mesmos estados e mesma logica de L40. Voce ja sabe montar isso!',
      ] },
    },
    boardWords: ['dd', 'abbdd', 'adcccd'],
    guidedLesson: [
      { text: 'Revisão de L40! a* b-pares d c-trios d.<br/>Aceitar: <b>dd</b>, <b>abbdd</b>, <b>adcccd</b>. Rejeitar: d, abd, abcdd.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Spotlight <b>dd</b>: núcleo q0→q2(d)→q5(final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Fix: q0→q2(d)→q5(final). "dd"✓. Próxima: "abbdd"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Spotlight <b>abbdd</b>: q0 lê "a" e "b" — sem seta! Preciso de loop a e q1 para b-pares.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Fix: q0 loop a, q0→q1(b)→q0(b). "abbdd"✓. Próxima: "adcccd"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 10, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Spotlight <b>adcccd</b>: q2 lê "c" — sem seta! Preciso de ciclo de c-trios.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 10, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Fix: q2→q3(c)→q4(c)→q2(c). "adcccd"✓ Concluído!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 10, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 48, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 40, y: 70, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 70, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'c' },
            { from: 'q4', to: 'q2', symbol: 'c' },
          ] } },
    ] },
  { id: 49, label: "L48", formula: "L = { w ∈ {0,1}* | zeros pares e uns ímpares }",                   desc: "",                                                                 shortestWord: "1",        regex: /^.*$/, validate: w => [...w].filter(c=>c==='0').length%2===0 && [...w].filter(c=>c==='1').length%2===1, alphabet: ['0', '1'],             acceptedWords: ["1","001","11100"],        rejectedWords: ["λ","0","01"],          hint: "Parecido com a L38, mas com números. Foque no estado correto de parada.",                                           successMsg: "Paridade binária.",
    tutorials: {
      onStart: { type: 'theory', title: 'Paridade Binária: 0-par e 1-ímpar!', dialog: [
        'L48: contar 0s e 1s separadamente. Aceito quando #0 par E #1 ímpar.',
        '"1" ✓ (0 zeros, 1 um). "001" ✓ (2 zeros, 1 um). "λ" ✗ (0 uns = par).',
        '4 combinações de paridade → 4 estados. Mesmo quadrado da L38 mas com 0 e 1!',
      ] },
      onDrawGraph: { type: 'mechanic', title: '4 Estados em Quadrado Binário', dialog: [
        'q0(ini)=(p0,p1), q1(f)=(p0,í1), q2=(í0,p1), q3=(í0,í1). Só q1 é final.',
        'Ler "1": q0↔q1 e q2↔q3. Ler "0": q0↔q2 e q1↔q3.',
        '"001": q0—0→q2—0→q0—1→q1(f) ✓. "11100": q0→q1→q0→q1—0→q3—0→q1(f) ✓.',
      ] },
    },
    boardWords: ['1', '001', '11100'],
    guidedLesson: [
      { text: 'Paridade binária: #0 par AND #1 ímpar!<br/>Aceitar: <b>1</b>, <b>001</b>, <b>11100</b>. Rejeitar: λ, 0, 01.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Spotlight <b>1</b>: raia do 1 — q0(ini)↔q1(final) via "1".',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Fix: q0↔q1(1). "1"✓. Próximas: "001" e "11100"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q1', to: 'q0', symbol: '1' },
          ] } },
      { text: 'Spotlight <b>001</b> e <b>11100</b>: q0 lê "0" — sem seta! Preciso de q2 e q3 para raia do 0.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q1', to: 'q0', symbol: '1' },
          ] } },
      { text: 'Fix: +q2,q3. q0↔q2(0), q1↔q3(0), q2↔q3(1). "001"✓ "11100"✓ Concluído!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 35, isInitial: false, isFinal: true  },
            { id: 'q2', label: 'q2', x: 25, y: 70, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 75, y: 70, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' }, { from: 'q1', to: 'q0', symbol: '1' },
            { from: 'q0', to: 'q2', symbol: '0' }, { from: 'q2', to: 'q0', symbol: '0' },
            { from: 'q1', to: 'q3', symbol: '0' }, { from: 'q3', to: 'q1', symbol: '0' },
            { from: 'q2', to: 'q3', symbol: '1' }, { from: 'q3', to: 'q2', symbol: '1' },
          ] } },
    ] },
  { id: 50, label: "L49", formula: "L = { a^n a c^m (ab+ba) c a^2p | n ≥ 0, m > 0, p > 0 }",          desc: "",                                                                 shortestWord: "acabcaa",  regex: /^a+c+(ab|ba)ca(aa)*$/,                                      alphabet: ['a', 'b', 'c'],        acceptedWords: ["acabcaa","aacabcaa","acbacaa"], rejectedWords: ["a","acabca","ab"], hint: "Na bifurcação no meio, o caminho pode ir por 'ab' ou por 'ba'.",                                                   successMsg: "Expressão bifurcada com sucesso.",
    tutorials: {
      onStart: { type: 'theory', title: 'a+ c+ (ab|ba) c aa+ — bifurcacao!', dialog: [
        'L49: a-s, c-s, depois "ab" OU "ba", depois c, depois pares de a (min 1 par).',
        '"acabcaa" ✓ (ab, 1par-a). "aacabcaa" ✓ (2a). "acbacaa" ✓ (ba).',
        '9 estados: q0-q2 (a/c loops), bifurcacao q3/q4, q5-q8 (cauda).',
      ] },
      onDrawGraph: { type: 'mechanic', title: '9 Estados: Loops + Bifurcacao', dialog: [
        'q0—a→q1 loop a. q1—c→q2 loop c. q2—a→q3—b→q5 (ab). q2—b→q4—a→q5 (ba).',
        'q5—c→q6—a→q7—a→q8(f). q8—a→q7 (mais pares).',
        '"acbacaa": q2—b→q4—a→q5→q6→q7→q8(f) ✓.',
      ] },
    },
    boardWords: ['acabcaa', 'aacabcaa', 'acbacaa'],
    guidedLesson: [
      { text: 'a+ c+ (ab|ba) c (aa)+. Bifurcacao no meio!<br/>Aceitar: <b>acabcaa</b>, <b>aacabcaa</b>, <b>acbacaa</b>. Rejeitar: a, acabca, ab.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Spotlight <b>acabcaa</b>: cadeia ab-branch + cauda, sem loops.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Fix: q0→q1(a)→q2(c)→q3(a)→q5(b)→q6(c)→q7(a)→q8(final,a)→q7(a). "acabcaa"✓. Próximas: "aacabcaa" e "acbacaa"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 22, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 36, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 50, y: 25, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 50, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 78, y: 50, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 88, y: 35, isInitial: false, isFinal: false },
            { id: 'q8', label: 'q8', x: 88, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q3', symbol: 'a' },
            { from: 'q3', to: 'q5', symbol: 'b' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q7', symbol: 'a' },
            { from: 'q7', to: 'q8', symbol: 'a' },
            { from: 'q8', to: 'q7', symbol: 'a' },
          ] } },
      { text: 'Spotlight <b>aacabcaa</b> e <b>acbacaa</b>: "aacabcaa" — q1 sem loop a! "acbacaa" — q2 sem seta "b" para branch ba.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 22, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 36, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 50, y: 25, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 50, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 78, y: 50, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 88, y: 35, isInitial: false, isFinal: false },
            { id: 'q8', label: 'q8', x: 88, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q3', symbol: 'a' },
            { from: 'q3', to: 'q5', symbol: 'b' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q7', symbol: 'a' },
            { from: 'q7', to: 'q8', symbol: 'a' },
            { from: 'q8', to: 'q7', symbol: 'a' },
          ] } },
      { text: 'Fix: q1 loop a, q2 loop c, +q4 para ba-branch q2→q4(b)→q5(a). "aacabcaa"✓ "acbacaa"✓ Concluído!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 22, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 36, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 50, y: 25, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 50, y: 75, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 50, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 78, y: 50, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 88, y: 35, isInitial: false, isFinal: false },
            { id: 'q8', label: 'q8', x: 88, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q3', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'b' },
            { from: 'q3', to: 'q5', symbol: 'b' },
            { from: 'q4', to: 'q5', symbol: 'a' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q7', symbol: 'a' },
            { from: 'q7', to: 'q8', symbol: 'a' },
            { from: 'q8', to: 'q7', symbol: 'a' },
          ] } },
    ] },
  { id: 51, label: "L50", formula: "L = { a^n b^m c^p | n, p > 0, m ≥ 0 e (n+p) é ímpar }",           desc: "",                                                                 shortestWord: "ac",       regex: /^.*$/, validate: w => /^a+b*c+$/.test(w) && ([...w].filter(c=>c==='a').length + [...w].filter(c=>c==='c').length)%2===1, alphabet: ['a', 'b', 'c'],        acceptedWords: ["acc","aac","abcc"],       rejectedWords: ["ac","aacc","c"],        hint: "Se a quantidade de 'a's for ímpar, os 'c's precisam ser pares, e vice versa.",                                     successMsg: "Paridade correlacionada funcionando!",
    tutorials: {
      onStart: { type: 'theory', title: 'a+ b* c+ com (n+p) impar!', dialog: [
        'L50: a^n b^m c^p. n>0, p>0, m>=0. Mas a quantidade (n+p) tem que ser impar.',
        '"acc" ✓ (1a+2c=3 impar). "aac" ✓ (2a+1c=3). "abcc" ✓ (1a+2c=3).',
        '"ac" ✗ (1+1=2 par). "aacc" ✗ (2+2=4 par). 7 estados: paridade de a e c.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '7 Estados: Paridade a + c', dialog: [
        'q0—a→q1 (impar-a). q1—a→q2 (par-a). q2—a→q1 (ciclo). q1—c→q5, q2—c→q6(f).',
        'b-phase: q1—b→q4(impar), q2—b→q3(par). q3,q4 loop b. q3—c→q6(f), q4—c→q5.',
        'c-phase: q5—c→q6(f). q6—c→q5. "abcc": q1—b→q4—c→q5—c→q6(f) ✓.',
      ] },
    },
    boardWords: ['acc', 'aac', 'abcc'],
    guidedLesson: [
      { text: 'a+ b* c+ com (n+p) impar!<br/>Aceitar: <b>acc</b>, <b>aac</b>, <b>abcc</b>. Rejeitar: ac, aacc, c.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Spotlight <b>acc</b>: caminho ímpar-a — q0→q1(a)→q5(c)→q6(final,c).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Fix: q0→q1(a)→q5(c)→q6(final)↔q5(c). "acc"✓. Próxima: "aac"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 82, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
      { text: 'Spotlight <b>aac</b>: q1 lê segundo "a" — sem seta! Preciso de q2 para par-a.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 82, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
      { text: 'Fix: +q2, q1↔q2(a), q2→q6(c). "aac"✓. Próxima: "abcc"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 82, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q5', symbol: 'c' },
            { from: 'q2', to: 'q6', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
      { text: 'Spotlight <b>abcc</b>: q1 lê "b" — sem seta! Preciso de q3,q4 para b-phase.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 82, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q5', symbol: 'c' },
            { from: 'q2', to: 'q6', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
      { text: 'Fix: +q4,q3. q1→q4(b,loop b), q2→q3(b,loop b), q4→q5(c), q3→q6(c). "abcc"✓ Concluído!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 28, y: 65, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 46, y: 65, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 82, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q4', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q3', symbol: 'b' },
            { from: 'q4', to: 'q4', symbol: 'b' },
            { from: 'q1', to: 'q5', symbol: 'c' },
            { from: 'q2', to: 'q6', symbol: 'c' },
            { from: 'q3', to: 'q6', symbol: 'c' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
    ] },
  { id: 52, label: "L52", formula: "L = { a^n b^m c^p | n > 0 (par), m (ímpar), p (par) }",            desc: "",                                                                 shortestWord: "aab",      regex: /^(aa)+(bb)*b(cc)*$/,                                        alphabet: ['a', 'b', 'c'],        acceptedWords: ["aab","aabcc","aaaabbb"],  rejectedWords: ["ab","aabb","b"],        hint: "É um trem de paridade. Vá de vagão em vagão cuidando da regra de cada letra.",                                     successMsg: "Combo triplo de paridades concluído.",
    tutorials: {
      onStart: { type: 'theory', title: '(aa)+ (bb)*b (cc)*: tres paridades!', dialog: [
        'L52: a-s em quantidade par (>=2), b-s impares (1,3,5...), c-s pares (0,2,4...).',
        '"aab" ✓ (2a,1b,0c). "aabcc" ✓ (2a,1b,2c). "aaaabbb" ✓ (4a,3b,0c).',
        '"ab" ✗ (1a=impar). "aabb" ✗ (2b=par). 7 estados encadeados.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '7 Estados: Trem de Paridade', dialog: [
        'aa-chain: q0—a→q1—a→q2. q2—a→q1 (mais pares). q2—b→q4(f,1b-impar).',
        'b-phase: q4—b→q3(par), q3—b→q4(impar). q4 e final.',
        'c-phase: q4—c→q5—c→q6(f). q6—c→q5. "aaaabbb": q2→q1→q2—b→q4—b→q3—b→q4(f) ✓.',
      ] },
    },
    boardWords: ['aab', 'aabcc', 'aaaabbb'],
    guidedLesson: [
      { text: '(aa)+ (bb)*b (cc)*: par-a, impar-b, par-c!<br/>Aceitar: <b>aab</b>, <b>aabcc</b>, <b>aaaabbb</b>. Rejeitar: ab, aabb, b.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Spotlight <b>aab</b>: núcleo q0→q1(a)→q2(a)→q4(final,b).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Fix: q0→q1(a)→q2(a)→q4(final,b). "aab"✓. Próxima: "aabcc"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 26, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 42, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'b' },
          ] } },
      { text: 'Spotlight <b>aabcc</b>: q4 lê "c" — sem seta! Preciso de q5,q6 para c-phase.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 26, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 42, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'b' },
          ] } },
      { text: 'Fix: +q5,q6. q4→q5(c)→q6(final)↔q5(c). "aabcc"✓. Próxima: "aaaabbb"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 26, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 42, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 40, isInitial: false, isFinal: true  },
            { id: 'q5', label: 'q5', x: 74, y: 40, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
      { text: 'Spotlight <b>aaaabbb</b>: q2 lê terceiro "a" — sem ciclo! q4 lê segundo "b" — sem seta! Preciso de q2→q1(a) e q3 para b-pares.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 26, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 42, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 40, isInitial: false, isFinal: true  },
            { id: 'q5', label: 'q5', x: 74, y: 40, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
      { text: 'Fix: q2→q1(a), +q3, q4→q3(b)→q4(b). "aaaabbb"✓ Concluído!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 26, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 42, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 40, isInitial: false, isFinal: true  },
            { id: 'q3', label: 'q3', x: 58, y: 68, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 74, y: 40, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
    ] },
  { id: 53, label: "L53", formula: "L = { w ∈ {a,b,c}* | cada b é seguido de pelo menos um c }",       desc: "",                                                                 shortestWord: "",         regex: /^(a|c|bc+)*$/,                                              alphabet: ['a', 'b', 'c'],        acceptedWords: ["λ","a","bc","abc"],       rejectedWords: ["b","ab","bcb"],         hint: "Leu um 'b'? A próxima letra TEM que ser 'c'. Depois tudo fica livre.",                                              successMsg: "Condicional restrita dominada. Zerou a lista!",
    tutorials: {
      onStart: { type: 'theory', title: 'Cada "b" deve ser seguido de "c"!', dialog: [
        'L53: sempre que ler um "b", a próxima letra TEM que ser "c". Senão rejeita.',
        '"bc" ✓ "abc" ✓ "λ" ✓ "a" ✓. "b" ✗ (nenhum c após b). "bcb" ✗ (o 2º b não tem c).',
        'Apenas 2 estados: livre (q0) e esperando-c (q1). Simples mas rigoroso!',
      ] },
      onDrawGraph: { type: 'mechanic', title: '2 Estados: Livre e Esperando-c', dialog: [
        'q0(ini,f): loop a,c. Ler "b" → q1 (modo de espera).',
        'q1: ler "c" → q0 (volta ao livre). Ler "a" ou "b" → morto (sem seta = rejeição).',
        '"abc": q0—a→q0—b→q1—c→q0(f) ✓. "bcb": q0→q1→q0→q1(não-f) ✗.',
      ] },
    },
    boardWords: ['λ', 'a', 'bc', 'abc'],
    guidedLesson: [
      { text: 'Condicional: cada "b" deve ser seguido de pelo menos um "c"!<br/>Aceitar: <b>λ</b>, <b>a</b>, <b>bc</b>, <b>abc</b>. Rejeitar: b, ab, bcb.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Spotlight <b>λ</b> e <b>a</b>: ambas precisam apenas de q0(ini,final) com loop a e c.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Fix: q0(ini,final) loop a,c. λ✓ a✓. Próximas: "bc" e "abc"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [ { id: 'q0', label: 'q0', x: 50, y: 50, isInitial: true, isFinal: true } ],
          transitions: [ { from: 'q0', to: 'q0', symbol: 'a,c' } ] } },
      { text: 'Spotlight <b>bc</b> e <b>abc</b>: q0 lê "b" — sem seta! Preciso de q1 para esperar o "c".',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [ { id: 'q0', label: 'q0', x: 50, y: 50, isInitial: true, isFinal: true } ],
          transitions: [ { from: 'q0', to: 'q0', symbol: 'a,c' } ] } },
      { text: 'Fix: q0→q1(b)→q0(c). "bc"✓ "abc"✓ Concluído!',
        boardDoneUpTo: 4, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 30, y: 50, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 70, y: 50, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a,c' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'c' },
          ] } },
    ] },
];
