export const lote3 = [
  { id: 41, label: "L40", formula: "L = { a^n b^2m d c^3p d | n, m, p â‰¥ 0 }",                          desc: "",                                                                 shortestWord: "dd",       regex: /^a*(bb)*d(ccc)*d$/,                                         alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["dd","abbdd","adcccdd"],  rejectedWords: ["d","abd","abcdd"],     hint: "Essa Ã© grande! Blocos de 'b' em duplas, o primeiro 'd' serve de ponte, e 'c' em trios.",                            successMsg: "Sintaxe complexa analisada com sucesso.",
    tutorials: {
      onStart: { type: 'theory', title: 'Blocos: a-block, b-pares, d, c-trios, d!', dialog: [
        'L40: a^n b^2m d c^3p d. a-s, depois b-pares, depois d, depois c-trios, depois d.',
        '"dd" âœ“ (0a 0b 0c). "abbdd" âœ“ (1a 1par-b). "adcccd" âœ“ (1a 1trio-c).',
        '6 estados: q0(ini), q1(b-impar), q2(apos-d), q3(c-1), q4(c-2), q5(f).',
      ] },
      onDrawGraph: { type: 'mechanic', title: '6 Estados em Sequencia', dialog: [
        'q0 loop a. q0â€”bâ†’q1â€”bâ†’q0 (pares). q0â€”dâ†’q2 (ponte).',
        'q2â€”dâ†’q5(f). q2â€”câ†’q3â€”câ†’q4â€”câ†’q2 (trio completo volta a q2).',
        '"adcccd": q0â€”aâ†’q0â€”dâ†’q2â€”câ†’q3â€”câ†’q4â€”câ†’q2â€”dâ†’q5(f) âœ“.',
      ] },
    },
    boardWords: ['dd', 'abbdd', 'adcccd'],
    guidedLesson: [
      { text: 'Blocos sequenciais: a* â€” b-pares â€” d â€” c-trios â€” d!<br/>Aceitar: <b>dd</b>, <b>abbdd</b>, <b>adcccd</b>. Rejeitar: d, abd, abcdd.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>dd</b>: nÃºcleo q0â†’q2(d)â†’q5(final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q2(d)â†’q5(final). "dd"âœ“. PrÃ³xima: "abbdd"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Foco em <b>abbdd</b>: q0 lÃª "a" e "b" â€” sem seta! Preciso de loop a e q1 para b-pares.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Solução: q0 loop a, q0â†’q1(b)â†’q0(b). "abbdd"âœ“. PrÃ³xima: "adcccd"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 10, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Foco em <b>adcccd</b>: q2 lÃª "c" â€” sem seta! Preciso de ciclo de c-trios.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 10, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Solução: q2â†’q3(c)â†’q4(c)â†’q2(c). "adcccd"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 10, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 48, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 40, y: 70, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 70, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'c' },
            { from: 'q4', to: 'q2', symbol: 'c' },
          ] } },
    ] },
  { id: 42, label: "L41", formula: "L = { a(dcb)^n a^m (bb)^p | n > 0, m > 0, p â‰¥ 0 }",               desc: "",                                                                 shortestWord: "adcba",    regex: /^a(dcb)+a+(bb)*$/,                                          alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["adcba","adcbaa","adcbabb"], rejectedWords: ["a","adcb","dcba"],  hint: "Siga a receita passo a passo, o ciclo 'dcb' Ã© o coraÃ§Ã£o do automato.",                                              successMsg: "Ciclo gigante dominado.",
    tutorials: {
      onStart: { type: 'theory', title: 'Ciclo dcb: a + dcb+ + a+ + b-pares!', dialog: [
        'L41: "a", depois 1+ ciclos de "dcb", depois 1+ "a", depois b-pares opcionais.',
        '"adcba" âœ“ (1 ciclo, 1a). "adcbaa" âœ“ (1 ciclo, 2a). "adcbabb" âœ“ (1a, 1par-b).',
        '"a" âœ— (sem dcb). "adcb" âœ— (sem a final). 7 estados em cadeia.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '7 Estados: Cadeia + Ciclo + b-pares', dialog: [
        'q0â€”aâ†’q1â€”dâ†’q2â€”câ†’q3â€”bâ†’q4 (ciclo dcb). q4â€”dâ†’q2 (repetir ciclo).',
        'q4â€”aâ†’q5(f). q5 loop a. q5â€”bâ†’q6â€”bâ†’q5 (pares de b).',
        '"adcbabb": q0â†’q1â†’q2â†’q3â†’q4â†’q5â€”bâ†’q6â€”bâ†’q5(f) âœ“.',
      ] },
    },
    boardWords: ['adcba', 'adcbaa', 'adcbabb'],
    guidedLesson: [
      { text: 'Ciclo dcb! a + (dcb)+ + a+ + (bb)*<br/>Aceitar: <b>adcba</b>, <b>adcbaa</b>, <b>adcbabb</b>. Rejeitar: a, adcb, dcba.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>adcba</b>: cadeia q0â†’q1(a)â†’q2(d)â†’q3(c)â†’q4(b) + ciclo q4â†’q2(d) e saÃ­da q4â†’q5(final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: cadeia + ciclo. "adcba"âœ“. PrÃ³xima: "adcbaa"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 24, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 40, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 56, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 72, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q2', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'a' },
          ] } },
      { text: 'Foco em <b>adcbaa</b>: q5 lÃª segundo "a" â€” sem loop! Preciso de q5â†’q5(a).',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 24, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 40, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 56, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 72, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q2', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'a' },
          ] } },
      { text: 'Solução: q5 loop a. "adcbaa"âœ“. PrÃ³xima: "adcbabb"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 24, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 40, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 56, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 72, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q2', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'a' },
            { from: 'q5', to: 'q5', symbol: 'a' },
          ] } },
      { text: 'Foco em <b>adcbabb</b>: q5 lÃª "b" â€” sem seta! Preciso de q6 para b-pares.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 24, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 40, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 56, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 72, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q2', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'a' },
            { from: 'q5', to: 'q5', symbol: 'a' },
          ] } },
      { text: 'Solução: q5â†’q6(b)â†’q5(b). "adcbabb"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 24, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 40, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 56, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 72, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
            { id: 'q6', label: 'q6', x: 88, y: 70, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q2', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'a' },
            { from: 'q5', to: 'q5', symbol: 'a' },
            { from: 'q5', to: 'q6', symbol: 'b' },
            { from: 'q6', to: 'q5', symbol: 'b' },
          ] } },
    ] },
  { id: 43, label: "L42", formula: "L = { a^n b^2m c c d^p | n > 0 (Ã­mpar), m, p â‰¥ 0 }",              desc: "",                                                                 shortestWord: "acc",      regex: /^a(aa)*(bb)*ccd*$/,                                         alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["acc","aaacc","accdd"],   rejectedWords: ["cc","aacc","abcc"],    hint: "O inÃ­cio exige vai-e-volta Ã­mpar para os 'a's, depois 'b's em duplas.",                                             successMsg: "Paridade e duplas em sequÃªncia perfeita.",
    tutorials: {
      onStart: { type: 'theory', title: 'a-Ã­mpar + b-pares + cc + d*!', dialog: [
        'L42: a^n b^2m cc d^p onde n > 0 Ã­mpar, m â‰¥ 0, p â‰¥ 0.',
        '"acc" âœ“ (1a, 0b). "aaacc" âœ“ (3a, 0b). "abbcc" âœ“ (1a, 2b). "aacc" âœ— (2a = par!).',
        '6 estados: q0 (start), q1 (odd-a), q2 (even-a), q3 (odd-b), q4 (1Âºc), q5 (final).',
      ] },
      onDrawGraph: { type: 'mechanic', title: '6 Estados: Paridade + Cadeia', dialog: [
        'q0â€”aâ†’q1â†”q2(a). q1 = a-Ã­mpar (vÃ¡lido). q2 = a-par (precisa de mais um "a").',
        'q1â€”câ†’q4â€”câ†’q5(f). q5 loop d. "cc" obrigatÃ³rio antes dos d\'s.',
        'q1â€”bâ†’q3â€”bâ†’q1. Pares de "b" retornam a q1. Ãmpar de "b" trava em q3.',
      ] },
    },
    boardWords: ['acc', 'aaacc', 'abbcc', 'accdd'],
    guidedLesson: [
      { text: 'a-Ã­mpar + b-pares + cc + d*!<br/>Aceitar: <b>acc</b>, <b>aaacc</b>, <b>abbcc</b>, <b>accdd</b>. Rejeitar: cc, aacc, abcc.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>acc</b> e <b>aaacc</b>: ambas precisam de paridade-a (q1â†”q2) + cadeia cc.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1â†”q2(a), q1â†’q4(c)â†’q5(final,loop d). "acc"âœ“ "aaacc"âœ“. PrÃ³ximas: "abbcc" e "accdd"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 48, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 68, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q4', symbol: 'c' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Foco em <b>abbcc</b> e <b>accdd</b>: "abbcc" â€” q1 sem seta para "b"! Preciso de q3 para b-pares.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 48, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 68, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q4', symbol: 'c' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Solução: +q3, q1â†’q3(b)â†’q1(b). "abbcc"âœ“ "accdd"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 4, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 48, y: 35, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 28, y: 70, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 68, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q4', symbol: 'c' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q5', symbol: 'd' },
          ] } },
    ] },
  { id: 44, label: "L43", formula: "L = { w âˆˆ {a,b,c,d}* | subpalavra 'ab' e sufixo 'cd' }",           desc: "",                                                                 shortestWord: "abcd",     regex: /^[abcd]*ab[abcd]*cd$/,                                      alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["abcd","aabcd","abccd"],  rejectedWords: ["Î»","acd","abdc"],      hint: "Ache primeiro o 'ab'. Depois de achar, fique aguardando um 'cd' para finalizar.",                                   successMsg: "Subpalavra + Sufixo resolvido.",
    tutorials: {
      onStart: { type: 'theory', title: 'Subpalavra "ab" + Sufixo "cd"!', dialog: [
        'L43: a palavra deve conter "ab" em algum lugar E terminar com "cd".',
        '"abcd" âœ“ (ab subpalavra, cd sufixo). "aabcd" âœ“. "abccd" âœ“.',
        '"acd" âœ— (sem "ab"). "abdc" âœ— ("ab" ok mas nÃ£o termina em "cd").',
      ] },
      onDrawGraph: { type: 'mechanic', title: '5 Estados: Detectar + Esperar', dialog: [
        'q0â†’q1(a): buscando "ab". q1â†’q2(b): "ab" encontrado! q0 e q1 voltam com c,d.',
        'q2â†’q3(c): primeiro "c" do sufixo. q3â†’q4(d): "cd" completo â€” final!',
        'q2 e q4 loop em a,b,d. q3 loop em c. Mismatches em q0,q1 voltam ao inÃ­cio.',
      ] },
    },
    boardWords: ['abcd', 'aabcd', 'abccd'],
    guidedLesson: [
      { text: 'Subpalavra "ab" e sufixo "cd"!<br/>Aceitar: <b>abcd</b>, <b>aabcd</b>, <b>abccd</b>. Rejeitar: Î», acd, abdc.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>abcd</b>: cadeia simples q0â†’q1(a)â†’q2(b)â†’q3(c)â†’q4(final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: cadeia q0â†’q1(a)â†’q2(b)â†’q3(c)â†’q4(final,d). "abcd"âœ“. PrÃ³ximas: "aabcd" e "abccd"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 50, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
          ] } },
      { text: 'Foco em <b>aabcd</b> e <b>abccd</b>: "aabcd" â€” q1 sem loop a! "abccd" â€” q3 sem loop c! Preciso de loops e retornos.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 50, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
          ] } },
      { text: 'Fix loops/retornos: q0 loop b,c,d; q1 loop a, q1â†’q0(c,d); q2 loop a,b,d; q3 loop c; q4â†’q3(c), q4â†’q2(a,b,d). "aabcd"âœ“ "abccd"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 50, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'b,c,d' },
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'c,d' },
            { from: 'q2', to: 'q2', symbol: 'a,b,d' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q2', symbol: 'a,b' },
            { from: 'q3', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
            { from: 'q4', to: 'q2', symbol: 'a,b,d' },
            { from: 'q4', to: 'q3', symbol: 'c' },
          ] } },
    ] },
  { id: 45, label: "L44", formula: "L = { w âˆˆ {a,b,c,d}* | prefixo 'abcd' e sufixo 'dcba' }",          desc: "",                                                                 shortestWord: "abcddcba", regex: /^abcd[abcd]*dcba$/,                                         alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["abcddcba","abcdadcba"],  rejectedWords: ["abcd","dcba","abcdcd"], hint: "SanduÃ­che de palavras! O comeÃ§o e o fim sÃ£o engessados.",                                                           successMsg: "SanduÃ­che de letras perfeito.",
    tutorials: {
      onStart: { type: 'theory', title: 'Prefixo "abcd" E sufixo "dcba"!', dialog: [
        'L44: comecar com "abcd" obrigatorio, terminar com "dcba" obrigatorio.',
        '"abcddcba" âœ“ (min, sobreposicao). "abcdadcba" âœ“ (1a no meio).',
        '"abcd" âœ— (falta sufixo). "dcba" âœ— (falta prefixo). 9 estados.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '9 Estados: Prefixo + Sufixo', dialog: [
        'Prefixo: q0â€”aâ†’q1â€”bâ†’q2â€”câ†’q3â€”dâ†’q4. Sufixo: q4â€”dâ†’q5â€”câ†’q6â€”bâ†’q7â€”aâ†’q8(f).',
        'q4 loop a,b,c. q5 loop d; q5â€”a,bâ†’q4. q6â€”a,câ†’q4; q6â€”dâ†’q5.',
        'q7â€”b,câ†’q4; q7â€”dâ†’q5. q8â€”a,b,câ†’q4; q8â€”dâ†’q5.',
      ] },
    },
    boardWords: ['abcddcba', 'abcdadcba'],
    guidedLesson: [
      { text: 'Sanduiche: prefixo "abcd" obrigatorio + sufixo "dcba" obrigatorio!<br/>Aceitar: <b>abcddcba</b>, <b>abcdadcba</b>. Rejeitar: abcd, dcba.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>abcddcba</b>: dois prefixos e sufixos em cadeia linear de 9 estados.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: cadeia q0â†’â€¦â†’q4(d)â†’q5(d)â†’q6(c)â†’q7(b)â†’q8(final,a). "abcddcba"âœ“. PrÃ³xima: "abcdadcba"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 21, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 34, y: 35, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 47, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 60, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 73, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 86, y: 35, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 86, y: 65, isInitial: false, isFinal: false },
            { id: 'q8', label: 'q8', x: 73, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'd' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q7', symbol: 'b' },
            { from: 'q7', to: 'q8', symbol: 'a' },
          ] } },
      { text: 'Foco em <b>abcdadcba</b>: q4 lÃª "a" â€” sem loop! Preciso de loops e retornos em q4 e sufixo.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 21, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 34, y: 35, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 47, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 60, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 73, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 86, y: 35, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 86, y: 65, isInitial: false, isFinal: false },
            { id: 'q8', label: 'q8', x: 73, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
            { from: 'q4', to: 'q5', symbol: 'd' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q7', symbol: 'b' },
            { from: 'q7', to: 'q8', symbol: 'a' },
          ] } },
      { text: 'Fix loops/retornos: q4 loop a,b,c; q5 loop d, q5â†’q4(a,b); q6â†’q5(d), q6â†’q4(a,c); q7â†’q4(b,c); q8â†’q4(a,b,c). "abcdadcba"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 21, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 34, y: 35, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 47, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 60, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 73, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 86, y: 35, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 86, y: 65, isInitial: false, isFinal: false },
            { id: 'q8', label: 'q8', x: 73, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
            { from: 'q4', to: 'q4', symbol: 'a,b,c' },
            { from: 'q4', to: 'q5', symbol: 'd' },
            { from: 'q5', to: 'q4', symbol: 'a,b' },
            { from: 'q5', to: 'q5', symbol: 'd' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q4', symbol: 'a,c' },
            { from: 'q6', to: 'q5', symbol: 'd' },
            { from: 'q6', to: 'q7', symbol: 'b' },
            { from: 'q7', to: 'q4', symbol: 'b,c' },
            { from: 'q7', to: 'q5', symbol: 'd' },
            { from: 'q7', to: 'q8', symbol: 'a' },
            { from: 'q8', to: 'q4', symbol: 'a,b,c' },
            { from: 'q8', to: 'q5', symbol: 'd' },
          ] } },
    ] },
  { id: 46, label: "L45", formula: "L = { w âˆˆ {a,b,c,d}* | pref 'abcd', sub 'cccc', suf 'dcba' }",    desc: "",                                                                 shortestWord: "abcdccccdcba", regex: /^abcd[abcd]*cccc[abcd]*dcba$/,                          alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["abcdccccdcba","abcdaccccdcba"], rejectedWords: ["abcddcba","abcdcccdcba","dcba"], hint: "FaÃ§a o caminho em trÃªs estÃ¡gios lÃ³gicos na sua cabeÃ§a.",                                          successMsg: "VocÃª construiu um autÃ´mato enorme, meus parabÃ©ns!",
    tutorials: {
      onStart: { type: 'theory', title: 'Prefixo abcd + 4c seguidos + sufixo dcba!', dialog: [
        'L45: comecar com "abcd", conter "cccc" em algum lugar, terminar com "dcba".',
        '"abcdccccdcba" âœ“ (min). "abcdaccccdcba" âœ“ (a no meio). 13 estados!',
        'Tres fases: prefixo fixo â†’ detectar cccc â†’ sufixo fixo.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '13 Estados: Tres Fases', dialog: [
        'Prefixo: q0â€”aâ†’q1â€”bâ†’q2â€”câ†’q3â€”dâ†’q4. q4 loop a,b,d; q4â€”câ†’q5.',
        'cccc: q5â€”câ†’q6â€”câ†’q7â€”câ†’q8. Mismatch volta a q4. q8 loop a,b,c.',
        'Sufixo: q8â€”dâ†’q9â€”câ†’q10â€”bâ†’q11â€”aâ†’q12(f). Mismatches â†’ q8 ou q9.',
      ] },
    },
    boardWords: ['abcdccccdcba', 'abcdaccccdcba'],
    guidedLesson: [
      { text: 'Tres fases: prefixo "abcd" + subpalavra "cccc" + sufixo "dcba"!<br/>Aceitar: <b>abcdccccdcba</b>, <b>abcdaccccdcba</b>. Rejeitar: abcddcba, abcdcccdcba.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>abcdccccdcba</b>: cadeia linear de 13 estados â€” prefixo + 4c + sufixo.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: cadeia q0â†’â€¦â†’q4(c)â†’q5(c)â†’q6(c)â†’q7(c)â†’q8(d)â†’q9(c)â†’q10(b)â†’q11(a)â†’q12(final). "abcdccccdcba"âœ“. PrÃ³xima: "abcdaccccdcba"!',
        boardDoneUpTo: 1,
        stateUpdate: {
          nodes: [
            { id: 'q0',  label: 'q0',  x:  6, y: 28, isInitial: true,  isFinal: false },
            { id: 'q1',  label: 'q1',  x: 14, y: 28, isInitial: false, isFinal: false },
            { id: 'q2',  label: 'q2',  x: 22, y: 28, isInitial: false, isFinal: false },
            { id: 'q3',  label: 'q3',  x: 30, y: 28, isInitial: false, isFinal: false },
            { id: 'q4',  label: 'q4',  x: 38, y: 28, isInitial: false, isFinal: false },
            { id: 'q5',  label: 'q5',  x: 47, y: 28, isInitial: false, isFinal: false },
            { id: 'q6',  label: 'q6',  x: 56, y: 28, isInitial: false, isFinal: false },
            { id: 'q7',  label: 'q7',  x: 65, y: 28, isInitial: false, isFinal: false },
            { id: 'q8',  label: 'q8',  x: 74, y: 28, isInitial: false, isFinal: false },
            { id: 'q9',  label: 'q9',  x: 74, y: 68, isInitial: false, isFinal: false },
            { id: 'q10', label: 'q10', x: 65, y: 68, isInitial: false, isFinal: false },
            { id: 'q11', label: 'q11', x: 56, y: 68, isInitial: false, isFinal: false },
            { id: 'q12', label: 'q12', x: 47, y: 68, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0',  to: 'q1',  symbol: 'a' },
            { from: 'q1',  to: 'q2',  symbol: 'b' },
            { from: 'q2',  to: 'q3',  symbol: 'c' },
            { from: 'q3',  to: 'q4',  symbol: 'd' },
            { from: 'q4',  to: 'q5',  symbol: 'c' },
            { from: 'q5',  to: 'q6',  symbol: 'c' },
            { from: 'q6',  to: 'q7',  symbol: 'c' },
            { from: 'q7',  to: 'q8',  symbol: 'c' },
            { from: 'q8',  to: 'q9',  symbol: 'd' },
            { from: 'q9',  to: 'q10', symbol: 'c' },
            { from: 'q10', to: 'q11', symbol: 'b' },
            { from: 'q11', to: 'q12', symbol: 'a' },
          ],
        } },
      { text: 'Foco em <b>abcdaccccdcba</b>: q4 lÃª "a" â€” sem loop! Preciso de loops e mismatches em q4 e fases cccc/sufixo.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0',  label: 'q0',  x:  6, y: 28, isInitial: true,  isFinal: false },
            { id: 'q1',  label: 'q1',  x: 14, y: 28, isInitial: false, isFinal: false },
            { id: 'q2',  label: 'q2',  x: 22, y: 28, isInitial: false, isFinal: false },
            { id: 'q3',  label: 'q3',  x: 30, y: 28, isInitial: false, isFinal: false },
            { id: 'q4',  label: 'q4',  x: 38, y: 28, isInitial: false, isFinal: false },
            { id: 'q5',  label: 'q5',  x: 47, y: 28, isInitial: false, isFinal: false },
            { id: 'q6',  label: 'q6',  x: 56, y: 28, isInitial: false, isFinal: false },
            { id: 'q7',  label: 'q7',  x: 65, y: 28, isInitial: false, isFinal: false },
            { id: 'q8',  label: 'q8',  x: 74, y: 28, isInitial: false, isFinal: false },
            { id: 'q9',  label: 'q9',  x: 74, y: 68, isInitial: false, isFinal: false },
            { id: 'q10', label: 'q10', x: 65, y: 68, isInitial: false, isFinal: false },
            { id: 'q11', label: 'q11', x: 56, y: 68, isInitial: false, isFinal: false },
            { id: 'q12', label: 'q12', x: 47, y: 68, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0',  to: 'q1',  symbol: 'a' },
            { from: 'q1',  to: 'q2',  symbol: 'b' },
            { from: 'q2',  to: 'q3',  symbol: 'c' },
            { from: 'q3',  to: 'q4',  symbol: 'd' },
            { from: 'q4',  to: 'q5',  symbol: 'c' },
            { from: 'q5',  to: 'q6',  symbol: 'c' },
            { from: 'q6',  to: 'q7',  symbol: 'c' },
            { from: 'q7',  to: 'q8',  symbol: 'c' },
            { from: 'q8',  to: 'q9',  symbol: 'd' },
            { from: 'q9',  to: 'q10', symbol: 'c' },
            { from: 'q10', to: 'q11', symbol: 'b' },
            { from: 'q11', to: 'q12', symbol: 'a' },
          ] } },
      { text: 'Fix loops/mismatches: q4 loop a,b,d; q5-q7 mismatchâ†’q4; q8 loop a,b,c; q9 loop d, q9â†’q8(a,b); sufixo mismatchesâ†’q8. "abcdaccccdcba"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 2,
        stateUpdate: {
          nodes: [
            { id: 'q0',  label: 'q0',  x:  6, y: 28, isInitial: true,  isFinal: false },
            { id: 'q1',  label: 'q1',  x: 14, y: 28, isInitial: false, isFinal: false },
            { id: 'q2',  label: 'q2',  x: 22, y: 28, isInitial: false, isFinal: false },
            { id: 'q3',  label: 'q3',  x: 30, y: 28, isInitial: false, isFinal: false },
            { id: 'q4',  label: 'q4',  x: 38, y: 28, isInitial: false, isFinal: false },
            { id: 'q5',  label: 'q5',  x: 47, y: 28, isInitial: false, isFinal: false },
            { id: 'q6',  label: 'q6',  x: 56, y: 28, isInitial: false, isFinal: false },
            { id: 'q7',  label: 'q7',  x: 65, y: 28, isInitial: false, isFinal: false },
            { id: 'q8',  label: 'q8',  x: 74, y: 28, isInitial: false, isFinal: false },
            { id: 'q9',  label: 'q9',  x: 74, y: 68, isInitial: false, isFinal: false },
            { id: 'q10', label: 'q10', x: 65, y: 68, isInitial: false, isFinal: false },
            { id: 'q11', label: 'q11', x: 56, y: 68, isInitial: false, isFinal: false },
            { id: 'q12', label: 'q12', x: 47, y: 68, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0',  to: 'q1',  symbol: 'a' },
            { from: 'q1',  to: 'q2',  symbol: 'b' },
            { from: 'q2',  to: 'q3',  symbol: 'c' },
            { from: 'q3',  to: 'q4',  symbol: 'd' },
            { from: 'q4',  to: 'q4',  symbol: 'a,b,d' },
            { from: 'q4',  to: 'q5',  symbol: 'c' },
            { from: 'q5',  to: 'q4',  symbol: 'a,b,d' },
            { from: 'q5',  to: 'q6',  symbol: 'c' },
            { from: 'q6',  to: 'q4',  symbol: 'a,b,d' },
            { from: 'q6',  to: 'q7',  symbol: 'c' },
            { from: 'q7',  to: 'q4',  symbol: 'a,b,d' },
            { from: 'q7',  to: 'q8',  symbol: 'c' },
            { from: 'q8',  to: 'q8',  symbol: 'a,b,c' },
            { from: 'q8',  to: 'q9',  symbol: 'd' },
            { from: 'q9',  to: 'q8',  symbol: 'a,b' },
            { from: 'q9',  to: 'q9',  symbol: 'd' },
            { from: 'q9',  to: 'q10', symbol: 'c' },
            { from: 'q10', to: 'q8',  symbol: 'a,c' },
            { from: 'q10', to: 'q9',  symbol: 'd' },
            { from: 'q10', to: 'q11', symbol: 'b' },
            { from: 'q11', to: 'q8',  symbol: 'b,c' },
            { from: 'q11', to: 'q9',  symbol: 'd' },
            { from: 'q11', to: 'q12', symbol: 'a' },
            { from: 'q12', to: 'q8',  symbol: 'a,b,c' },
            { from: 'q12', to: 'q9',  symbol: 'd' },
          ],
        } },
    ] },
  { id: 47, label: "L46", formula: "L = { (a+b+c)* | qtd de a, b e c Ã© par }",                          desc: "",                                                                 shortestWord: "",         regex: /^.*$/, validate: w => ['a','b','c'].every(c => [...w].filter(x=>x===c).length%2===0), alphabet: ['a', 'b', 'c'],        acceptedWords: ["Î»","aabb","aabbcc"],      rejectedWords: ["a","b","abc"],         hint: "Isso Ã© um cubo mÃ¡gico de estados! Paridade para 3 letras exige 8 estados.",                                        successMsg: "Paridade em 3D completada!",
    tutorials: {
      onStart: { type: 'theory', title: 'Cubo de paridade: 3 letras, 8 estados!', dialog: [
        'L46: contar a, b e c separadamente. Aceito quando TODOS pares.',
        '"Î»" âœ“ (0+0+0). "aabb" âœ“ (2a,2b,0c). "aabbcc" âœ“ (2a,2b,2c). "a" âœ— (1a impar).',
        '8 combinacoes de paridade: 2^3 = 8 estados. Apenas q0(ini,f) aceita.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '8 Estados em Cubo', dialog: [
        'Linhas "a" (vertical): q0â†”q1, q2â†”q4, q3â†”q5, q6â†”q7.',
        'Linhas "b" (horizontal): q0â†”q2, q1â†”q4, q3â†”q6, q5â†”q7.',
        'Linhas "c" (cruzadas): q0â†”q3, q1â†”q5, q2â†”q6, q4â†”q7.',
      ] },
    },
    boardWords: ['Î»', 'aabb', 'aabbcc'],
    guidedLesson: [
      { text: 'Cubo de paridade: a, b e c todos pares!<br/>Aceitar: <b>Î»</b>, <b>aabb</b>, <b>aabbcc</b>. Rejeitar: a, b, abc.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>Î»</b>: palavra vazia â€” q0 inicial e final Ã© suficiente.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0(ini,final). Î»âœ“. PrÃ³xima: "aabb"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [ { id: 'q0', label: 'q0', x: 50, y: 50, isInitial: true, isFinal: true } ],
          transitions: [] } },
      { text: 'Foco em <b>aabb</b>: q0 lÃª "a" â€” sem seta! Preciso de raias a, b, c bidirecionais.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [ { id: 'q0', label: 'q0', x: 50, y: 50, isInitial: true, isFinal: true } ],
          transitions: [] } },
      { text: 'Solução: q0â†”q1(a), q0â†”q2(b), q0â†”q3(c). "aabb"âœ“. PrÃ³xima: "aabbcc"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 12, y: 25, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 12, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 37, y: 25, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 62, y: 25, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' }, { from: 'q1', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q2', symbol: 'b' }, { from: 'q2', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q3', symbol: 'c' }, { from: 'q3', to: 'q0', symbol: 'c' },
          ] } },
      { text: 'Foco em <b>aabbcc</b>: q1 e q2 sem seta "c"! Preciso dos 4 estados restantes do cubo.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 12, y: 25, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 12, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 37, y: 25, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 62, y: 25, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' }, { from: 'q1', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q2', symbol: 'b' }, { from: 'q2', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q3', symbol: 'c' }, { from: 'q3', to: 'q0', symbol: 'c' },
          ] } },
      { text: 'Solução: cubo completo +q4,q5,q6,q7. "aabbcc"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 12, y: 25, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 12, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 37, y: 25, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 62, y: 25, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 37, y: 70, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 62, y: 70, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 87, y: 25, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 87, y: 70, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' }, { from: 'q1', to: 'q0', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'a' }, { from: 'q4', to: 'q2', symbol: 'a' },
            { from: 'q3', to: 'q5', symbol: 'a' }, { from: 'q5', to: 'q3', symbol: 'a' },
            { from: 'q6', to: 'q7', symbol: 'a' }, { from: 'q7', to: 'q6', symbol: 'a' },
            { from: 'q0', to: 'q2', symbol: 'b' }, { from: 'q2', to: 'q0', symbol: 'b' },
            { from: 'q1', to: 'q4', symbol: 'b' }, { from: 'q4', to: 'q1', symbol: 'b' },
            { from: 'q3', to: 'q6', symbol: 'b' }, { from: 'q6', to: 'q3', symbol: 'b' },
            { from: 'q5', to: 'q7', symbol: 'b' }, { from: 'q7', to: 'q5', symbol: 'b' },
            { from: 'q0', to: 'q3', symbol: 'c' }, { from: 'q3', to: 'q0', symbol: 'c' },
            { from: 'q1', to: 'q5', symbol: 'c' }, { from: 'q5', to: 'q1', symbol: 'c' },
            { from: 'q2', to: 'q6', symbol: 'c' }, { from: 'q6', to: 'q2', symbol: 'c' },
            { from: 'q4', to: 'q7', symbol: 'c' }, { from: 'q7', to: 'q4', symbol: 'c' },
          ] } },
    ] },
  { id: 48, label: "L47", formula: "L = { a^n b^2m d c^3p d | n, m, p â‰¥ 0 }",                          desc: "(RevisÃ£o L40)",                                                    shortestWord: "dd",       regex: /^a*(bb)*d(ccc)*d$/,                                         alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["dd","abbdd","adcccdd"],  rejectedWords: ["d","abd","abcdd"],     hint: "Se chegou atÃ© aqui, jÃ¡ sabe: separe o problema em bloquinhos lÃ³gicos.",                                             successMsg: "RevisÃ£o bem sucedida.",
    tutorials: {
      onStart: { type: 'theory', title: 'RevisÃ£o L40: blocos a, b-pares, d, c-trios, d!', dialog: [
        'L47 e revisÃ£o de L40. Mesma linguagem a^n b^2m d c^3p d.',
        '"dd" âœ“. "abbdd" âœ“. "adcccd" âœ“. "d" âœ—. "abcdd" âœ—.',
        'Relembre os 6 estados: q0(ini), q1(b-impar), q2(apos-d), q3(c-1), q4(c-2), q5(f).',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Revisao: 6 Estados', dialog: [
        'q0 loop a; q0â€”bâ†’q1â€”bâ†’q0; q0â€”dâ†’q2.',
        'q2â€”dâ†’q5(f); q2â€”câ†’q3â€”câ†’q4â€”câ†’q2.',
        'Mesmos estados e mesma logica de L40. Voce ja sabe montar isso!',
      ] },
    },
    boardWords: ['dd', 'abbdd', 'adcccd'],
    guidedLesson: [
      { text: 'RevisÃ£o de L40! a* b-pares d c-trios d.<br/>Aceitar: <b>dd</b>, <b>abbdd</b>, <b>adcccd</b>. Rejeitar: d, abd, abcdd.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>dd</b>: nÃºcleo q0â†’q2(d)â†’q5(final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q2(d)â†’q5(final). "dd"âœ“. PrÃ³xima: "abbdd"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Foco em <b>abbdd</b>: q0 lÃª "a" e "b" â€” sem seta! Preciso de loop a e q1 para b-pares.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Solução: q0 loop a, q0â†’q1(b)â†’q0(b). "abbdd"âœ“. PrÃ³xima: "adcccd"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 10, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Foco em <b>adcccd</b>: q2 lÃª "c" â€” sem seta! Preciso de ciclo de c-trios.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 10, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 40, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
          ] } },
      { text: 'Solução: q2â†’q3(c)â†’q4(c)â†’q2(c). "adcccd"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 10, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 48, y: 40, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 40, y: 70, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 70, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 88, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'd' },
            { from: 'q2', to: 'q5', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'c' },
            { from: 'q4', to: 'q2', symbol: 'c' },
          ] } },
    ] },
  { id: 49, label: "L48", formula: "L = { w âˆˆ {0,1}* | zeros pares e uns Ã­mpares }",                   desc: "",                                                                 shortestWord: "1",        regex: /^.*$/, validate: w => [...w].filter(c=>c==='0').length%2===0 && [...w].filter(c=>c==='1').length%2===1, alphabet: ['0', '1'],             acceptedWords: ["1","001","11100"],        rejectedWords: ["Î»","0","01"],          hint: "Parecido com a L38, mas com nÃºmeros. Foque no estado correto de parada.",                                           successMsg: "Paridade binÃ¡ria.",
    tutorials: {
      onStart: { type: 'theory', title: 'Paridade BinÃ¡ria: 0-par e 1-Ã­mpar!', dialog: [
        'L48: contar 0s e 1s separadamente. Aceito quando #0 par E #1 Ã­mpar.',
        '"1" âœ“ (0 zeros, 1 um). "001" âœ“ (2 zeros, 1 um). "Î»" âœ— (0 uns = par).',
        '4 combinaÃ§Ãµes de paridade â†’ 4 estados. Mesmo quadrado da L38 mas com 0 e 1!',
      ] },
      onDrawGraph: { type: 'mechanic', title: '4 Estados em Quadrado BinÃ¡rio', dialog: [
        'q0(ini)=(p0,p1), q1(f)=(p0,Ã­1), q2=(Ã­0,p1), q3=(Ã­0,Ã­1). SÃ³ q1 Ã© final.',
        'Ler "1": q0â†”q1 e q2â†”q3. Ler "0": q0â†”q2 e q1â†”q3.',
        '"001": q0â€”0â†’q2â€”0â†’q0â€”1â†’q1(f) âœ“. "11100": q0â†’q1â†’q0â†’q1â€”0â†’q3â€”0â†’q1(f) âœ“.',
      ] },
    },
    boardWords: ['1', '001', '11100'],
    guidedLesson: [
      { text: 'Paridade binÃ¡ria: #0 par AND #1 Ã­mpar!<br/>Aceitar: <b>1</b>, <b>001</b>, <b>11100</b>. Rejeitar: Î», 0, 01.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>1</b>: raia do 1 â€” q0(ini)â†”q1(final) via "1".',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†”q1(1). "1"âœ“. PrÃ³ximas: "001" e "11100"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q1', to: 'q0', symbol: '1' },
          ] } },
      { text: 'Foco em <b>001</b> e <b>11100</b>: q0 lÃª "0" â€” sem seta! Preciso de q2 e q3 para raia do 0.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q1', to: 'q0', symbol: '1' },
          ] } },
      { text: 'Solução: +q2,q3. q0â†”q2(0), q1â†”q3(0), q2â†”q3(1). "001"âœ“ "11100"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 35, isInitial: false, isFinal: true  },
            { id: 'q2', label: 'q2', x: 25, y: 70, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 75, y: 70, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' }, { from: 'q1', to: 'q0', symbol: '1' },
            { from: 'q0', to: 'q2', symbol: '0' }, { from: 'q2', to: 'q0', symbol: '0' },
            { from: 'q1', to: 'q3', symbol: '0' }, { from: 'q3', to: 'q1', symbol: '0' },
            { from: 'q2', to: 'q3', symbol: '1' }, { from: 'q3', to: 'q2', symbol: '1' },
          ] } },
    ] },
  { id: 50, label: "L49", formula: "L = { a^n a c^m (ab+ba) c a^2p | n â‰¥ 0, m > 0, p > 0 }",          desc: "",                                                                 shortestWord: "acabcaa",  regex: /^a+c+(ab|ba)ca(aa)*$/,                                      alphabet: ['a', 'b', 'c'],        acceptedWords: ["acabcaa","aacabcaa","acbacaa"], rejectedWords: ["a","acabca","ab"], hint: "Na bifurcaÃ§Ã£o no meio, o caminho pode ir por 'ab' ou por 'ba'.",                                                   successMsg: "ExpressÃ£o bifurcada com sucesso.",
    tutorials: {
      onStart: { type: 'theory', title: 'a+ c+ (ab|ba) c aa+ â€” bifurcacao!', dialog: [
        'L49: a-s, c-s, depois "ab" OU "ba", depois c, depois pares de a (min 1 par).',
        '"acabcaa" âœ“ (ab, 1par-a). "aacabcaa" âœ“ (2a). "acbacaa" âœ“ (ba).',
        '9 estados: q0-q2 (a/c loops), bifurcacao q3/q4, q5-q8 (cauda).',
      ] },
      onDrawGraph: { type: 'mechanic', title: '9 Estados: Loops + Bifurcacao', dialog: [
        'q0â€”aâ†’q1 loop a. q1â€”câ†’q2 loop c. q2â€”aâ†’q3â€”bâ†’q5 (ab). q2â€”bâ†’q4â€”aâ†’q5 (ba).',
        'q5â€”câ†’q6â€”aâ†’q7â€”aâ†’q8(f). q8â€”aâ†’q7 (mais pares).',
        '"acbacaa": q2â€”bâ†’q4â€”aâ†’q5â†’q6â†’q7â†’q8(f) âœ“.',
      ] },
    },
    boardWords: ['acabcaa', 'aacabcaa', 'acbacaa'],
    guidedLesson: [
      { text: 'a+ c+ (ab|ba) c (aa)+. Bifurcacao no meio!<br/>Aceitar: <b>acabcaa</b>, <b>aacabcaa</b>, <b>acbacaa</b>. Rejeitar: a, acabca, ab.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>acabcaa</b>: cadeia ab-branch + cauda, sem loops.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1(a)â†’q2(c)â†’q3(a)â†’q5(b)â†’q6(c)â†’q7(a)â†’q8(final,a)â†’q7(a). "acabcaa"âœ“. PrÃ³ximas: "aacabcaa" e "acbacaa"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 22, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 36, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 50, y: 25, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 50, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 78, y: 50, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 88, y: 35, isInitial: false, isFinal: false },
            { id: 'q8', label: 'q8', x: 88, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q3', symbol: 'a' },
            { from: 'q3', to: 'q5', symbol: 'b' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q7', symbol: 'a' },
            { from: 'q7', to: 'q8', symbol: 'a' },
            { from: 'q8', to: 'q7', symbol: 'a' },
          ] } },
      { text: 'Foco em <b>aacabcaa</b> e <b>acbacaa</b>: "aacabcaa" â€” q1 sem loop a! "acbacaa" â€” q2 sem seta "b" para branch ba.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 22, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 36, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 50, y: 25, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 50, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 78, y: 50, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 88, y: 35, isInitial: false, isFinal: false },
            { id: 'q8', label: 'q8', x: 88, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q3', symbol: 'a' },
            { from: 'q3', to: 'q5', symbol: 'b' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q7', symbol: 'a' },
            { from: 'q7', to: 'q8', symbol: 'a' },
            { from: 'q8', to: 'q7', symbol: 'a' },
          ] } },
      { text: 'Solução: q1 loop a, q2 loop c, +q4 para ba-branch q2â†’q4(b)â†’q5(a). "aacabcaa"âœ“ "acbacaa"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x:  8, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 22, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 36, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 50, y: 25, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 50, y: 75, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 50, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 78, y: 50, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 88, y: 35, isInitial: false, isFinal: false },
            { id: 'q8', label: 'q8', x: 88, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q3', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'b' },
            { from: 'q3', to: 'q5', symbol: 'b' },
            { from: 'q4', to: 'q5', symbol: 'a' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q7', symbol: 'a' },
            { from: 'q7', to: 'q8', symbol: 'a' },
            { from: 'q8', to: 'q7', symbol: 'a' },
          ] } },
    ] },
  { id: 51, label: "L50", formula: "L = { a^n b^m c^p | n, p > 0, m â‰¥ 0 e (n+p) Ã© Ã­mpar }",           desc: "",                                                                 shortestWord: "ac",       regex: /^.*$/, validate: w => /^a+b*c+$/.test(w) && ([...w].filter(c=>c==='a').length + [...w].filter(c=>c==='c').length)%2===1, alphabet: ['a', 'b', 'c'],        acceptedWords: ["acc","aac","abcc"],       rejectedWords: ["ac","aacc","c"],        hint: "Se a quantidade de 'a's for Ã­mpar, os 'c's precisam ser pares, e vice versa.",                                     successMsg: "Paridade correlacionada funcionando!",
    tutorials: {
      onStart: { type: 'theory', title: 'a+ b* c+ com (n+p) impar!', dialog: [
        'L50: a^n b^m c^p. n>0, p>0, m>=0. Mas a quantidade (n+p) tem que ser impar.',
        '"acc" âœ“ (1a+2c=3 impar). "aac" âœ“ (2a+1c=3). "abcc" âœ“ (1a+2c=3).',
        '"ac" âœ— (1+1=2 par). "aacc" âœ— (2+2=4 par). 7 estados: paridade de a e c.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '7 Estados: Paridade a + c', dialog: [
        'q0â€”aâ†’q1 (impar-a). q1â€”aâ†’q2 (par-a). q2â€”aâ†’q1 (ciclo). q1â€”câ†’q5, q2â€”câ†’q6(f).',
        'b-phase: q1â€”bâ†’q4(impar), q2â€”bâ†’q3(par). q3,q4 loop b. q3â€”câ†’q6(f), q4â€”câ†’q5.',
        'c-phase: q5â€”câ†’q6(f). q6â€”câ†’q5. "abcc": q1â€”bâ†’q4â€”câ†’q5â€”câ†’q6(f) âœ“.',
      ] },
    },
    boardWords: ['acc', 'aac', 'abcc'],
    guidedLesson: [
      { text: 'a+ b* c+ com (n+p) impar!<br/>Aceitar: <b>acc</b>, <b>aac</b>, <b>abcc</b>. Rejeitar: ac, aacc, c.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>acc</b>: caminho Ã­mpar-a â€” q0â†’q1(a)â†’q5(c)â†’q6(final,c).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1(a)â†’q5(c)â†’q6(final)â†”q5(c). "acc"âœ“. PrÃ³xima: "aac"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 82, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
      { text: 'Foco em <b>aac</b>: q1 lÃª segundo "a" â€” sem seta! Preciso de q2 para par-a.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 82, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
      { text: 'Solução: +q2, q1â†”q2(a), q2â†’q6(c). "aac"âœ“. PrÃ³xima: "abcc"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 82, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q5', symbol: 'c' },
            { from: 'q2', to: 'q6', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
      { text: 'Foco em <b>abcc</b>: q1 lÃª "b" â€” sem seta! Preciso de q3,q4 para b-phase.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 35, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 82, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q5', symbol: 'c' },
            { from: 'q2', to: 'q6', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
      { text: 'Solução: +q4,q3. q1â†’q4(b,loop b), q2â†’q3(b,loop b), q4â†’q5(c), q3â†’q6(c). "abcc"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 28, y: 65, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 46, y: 65, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 82, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q4', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q3', symbol: 'b' },
            { from: 'q4', to: 'q4', symbol: 'b' },
            { from: 'q1', to: 'q5', symbol: 'c' },
            { from: 'q2', to: 'q6', symbol: 'c' },
            { from: 'q3', to: 'q6', symbol: 'c' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
    ] },
  { id: 52, label: "L52", formula: "L = { a^n b^m c^p | n > 0 (par), m (Ã­mpar), p (par) }",            desc: "",                                                                 shortestWord: "aab",      regex: /^(aa)+(bb)*b(cc)*$/,                                        alphabet: ['a', 'b', 'c'],        acceptedWords: ["aab","aabcc","aaaabbb"],  rejectedWords: ["ab","aabb","b"],        hint: "Ã‰ um trem de paridade. VÃ¡ de vagÃ£o em vagÃ£o cuidando da regra de cada letra.",                                     successMsg: "Combo triplo de paridades concluÃ­do.",
    tutorials: {
      onStart: { type: 'theory', title: '(aa)+ (bb)*b (cc)*: tres paridades!', dialog: [
        'L52: a-s em quantidade par (>=2), b-s impares (1,3,5...), c-s pares (0,2,4...).',
        '"aab" âœ“ (2a,1b,0c). "aabcc" âœ“ (2a,1b,2c). "aaaabbb" âœ“ (4a,3b,0c).',
        '"ab" âœ— (1a=impar). "aabb" âœ— (2b=par). 7 estados encadeados.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '7 Estados: Trem de Paridade', dialog: [
        'aa-chain: q0â€”aâ†’q1â€”aâ†’q2. q2â€”aâ†’q1 (mais pares). q2â€”bâ†’q4(f,1b-impar).',
        'b-phase: q4â€”bâ†’q3(par), q3â€”bâ†’q4(impar). q4 e final.',
        'c-phase: q4â€”câ†’q5â€”câ†’q6(f). q6â€”câ†’q5. "aaaabbb": q2â†’q1â†’q2â€”bâ†’q4â€”bâ†’q3â€”bâ†’q4(f) âœ“.',
      ] },
    },
    boardWords: ['aab', 'aabcc', 'aaaabbb'],
    guidedLesson: [
      { text: '(aa)+ (bb)*b (cc)*: par-a, impar-b, par-c!<br/>Aceitar: <b>aab</b>, <b>aabcc</b>, <b>aaaabbb</b>. Rejeitar: ab, aabb, b.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>aab</b>: nÃºcleo q0â†’q1(a)â†’q2(a)â†’q4(final,b).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1(a)â†’q2(a)â†’q4(final,b). "aab"âœ“. PrÃ³xima: "aabcc"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 26, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 42, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'b' },
          ] } },
      { text: 'Foco em <b>aabcc</b>: q4 lÃª "c" â€” sem seta! Preciso de q5,q6 para c-phase.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 26, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 42, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'b' },
          ] } },
      { text: 'Solução: +q5,q6. q4â†’q5(c)â†’q6(final)â†”q5(c). "aabcc"âœ“. PrÃ³xima: "aaaabbb"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 26, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 42, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 40, isInitial: false, isFinal: true  },
            { id: 'q5', label: 'q5', x: 74, y: 40, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
      { text: 'Foco em <b>aaaabbb</b>: q2 lÃª terceiro "a" â€” sem ciclo! q4 lÃª segundo "b" â€” sem seta! Preciso de q2â†’q1(a) e q3 para b-pares.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 26, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 42, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 40, isInitial: false, isFinal: true  },
            { id: 'q5', label: 'q5', x: 74, y: 40, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
      { text: 'Solução: q2â†’q1(a), +q3, q4â†’q3(b)â†’q4(b). "aaaabbb"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 40, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 26, y: 40, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 42, y: 40, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 40, isInitial: false, isFinal: true  },
            { id: 'q3', label: 'q3', x: 58, y: 68, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 74, y: 40, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 90, y: 40, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q2', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q4', symbol: 'b' },
            { from: 'q4', to: 'q5', symbol: 'c' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'c' },
          ] } },
    ] },
  { id: 53, label: "L53", formula: "L = { w âˆˆ {a,b,c}* | cada b Ã© seguido de pelo menos um c }",       desc: "",                                                                 shortestWord: "",         regex: /^(a|c|bc+)*$/,                                              alphabet: ['a', 'b', 'c'],        acceptedWords: ["Î»","a","bc","abc"],       rejectedWords: ["b","ab","bcb"],         hint: "Leu um 'b'? A prÃ³xima letra TEM que ser 'c'. Depois tudo fica livre.",                                              successMsg: "Condicional restrita dominada. Zerou a lista!",
    tutorials: {
      onStart: { type: 'theory', title: 'Cada "b" deve ser seguido de "c"!', dialog: [
        'L53: sempre que ler um "b", a prÃ³xima letra TEM que ser "c". SenÃ£o rejeita.',
        '"bc" âœ“ "abc" âœ“ "Î»" âœ“ "a" âœ“. "b" âœ— (nenhum c apÃ³s b). "bcb" âœ— (o 2Âº b nÃ£o tem c).',
        'Apenas 2 estados: livre (q0) e esperando-c (q1). Simples mas rigoroso!',
      ] },
      onDrawGraph: { type: 'mechanic', title: '2 Estados: Livre e Esperando-c', dialog: [
        'q0(ini,f): loop a,c. Ler "b" â†’ q1 (modo de espera).',
        'q1: ler "c" â†’ q0 (volta ao livre). Ler "a" ou "b" â†’ morto (sem seta = rejeiÃ§Ã£o).',
        '"abc": q0â€”aâ†’q0â€”bâ†’q1â€”câ†’q0(f) âœ“. "bcb": q0â†’q1â†’q0â†’q1(nÃ£o-f) âœ—.',
      ] },
    },
    boardWords: ['Î»', 'a', 'bc', 'abc'],
    guidedLesson: [
      { text: 'Condicional: cada "b" deve ser seguido de pelo menos um "c"!<br/>Aceitar: <b>Î»</b>, <b>a</b>, <b>bc</b>, <b>abc</b>. Rejeitar: b, ab, bcb.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>Î»</b> e <b>a</b>: ambas precisam apenas de q0(ini,final) com loop a e c.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0(ini,final) loop a,c. Î»âœ“ aâœ“. PrÃ³ximas: "bc" e "abc"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [ { id: 'q0', label: 'q0', x: 50, y: 50, isInitial: true, isFinal: true } ],
          transitions: [ { from: 'q0', to: 'q0', symbol: 'a,c' } ] } },
      { text: 'Foco em <b>bc</b> e <b>abc</b>: q0 lÃª "b" â€” sem seta! Preciso de q1 para esperar o "c".',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [ { id: 'q0', label: 'q0', x: 50, y: 50, isInitial: true, isFinal: true } ],
          transitions: [ { from: 'q0', to: 'q0', symbol: 'a,c' } ] } },
      { text: 'Solução: q0â†’q1(b)â†’q0(c). "bc"âœ“ "abc"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 4, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 30, y: 50, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 70, y: 50, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a,c' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'c' },
          ] } },
    ] },
];
