export const lote2 = [
  { id: 21, label: "L21", formula: "L = { w âˆˆ {a,b,c,d}* | a's precedem b's e c's precedem d's }",    desc: "",                                                                 shortestWord: "",         regex: /^a*b*c*d*$/,                                                alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["Î»","abcd","abc"],         rejectedWords: ["ba","ca","cb"],        hint: "Ã‰ uma progressÃ£o linear estrita pelo alfabeto.",                                                                    successMsg: "Ordem alfabÃ©tica mantida!",
    tutorials: {
      onStart: { type: 'theory', title: 'Ordem AlfabÃ©tica Estrita!', dialog: [
        'L21: sÃ­mbolos em ordem a* b* c* d* â€” cada bloco pode aparecer 0 ou mais vezes.',
        '"Î»", "abcd", "aabdd", "bbdd" â€” vÃ¡lidos. "ba" ou "ca" â€” invÃ¡lidos (ordem errada)!',
        'Uma vez que o AFD avanÃ§a para o bloco "b", nunca volta para "a". TransiÃ§Ãµes unidirecionais!',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Cadeia de Blocos com Atalhos', dialog: [
        '4 estados em zigue-zague: <b>q0</b>(a,ini,f), <b>q1</b>(b,f), <b>q2</b>(c,f), <b>q3</b>(d,f) â€” todos finais!',
        'Atalhos: q0â†’q3(d) e q1â†’q3(d). "ad" âœ” (pula b e c), "bd" âœ” (pula c), "cd" âœ” "d" âœ”',
        '"ba" Ã© rejeitado: q1 sem seta para "a". "cb" Ã© rejeitado: q2 sem seta para "b". A ordem importa!',
      ] },
    },
    boardWords: ['Î»', 'a', 'ab', 'abc', 'cd', 'abcd', 'ad', 'bd', 'd'],
    guidedLesson: [
      { text: '4 blocos em ordem: a* b* c* d* â€” todos opcionais!<br/>Aceitar: <b>Î»</b>, <b>a</b>, <b>ab</b>, <b>abc</b>, <b>cd</b>, <b>abcd</b>, <b>ad</b>, <b>bd</b>, <b>d</b>.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>Î»</b> e <b>a</b>: ambas no bloco "a". q0(ini,final) + loop a resolve as duas!',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0(ini,final) + loop a. Î»=q0âœ“, a=q0â†’q0âœ“. PrÃ³ximo: "ab"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [{ id: 'q0', label: 'q0', x: 20, y: 65, isInitial: true, isFinal: true }],
          transitions: [{ from: 'q0', to: 'q0', symbol: 'a' }] } },
      { text: 'Foco em <b>ab</b>: bloco b â€” q0 lÃª "b" sem seta! Preciso de q1(final, loop b).',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [{ id: 'q0', label: 'q0', x: 20, y: 65, isInitial: true, isFinal: true }],
          transitions: [{ from: 'q0', to: 'q0', symbol: 'a' }] } },
      { text: 'Solução: q0â†’q1(b,final,loop b). "ab" âœ“. PrÃ³ximas: "abc" e "cd"!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 20, y: 65, isInitial: true, isFinal: true },
            { id: 'q1', label: 'q1', x: 40, y: 35, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q1', symbol: 'b' },
          ] } },
      { text: 'Foco em <b>abc</b> e <b>cd</b>: q1 lÃª "c" sem seta! q2(final, loop c) com atalho q0â†’q2(c).',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 20, y: 65, isInitial: true, isFinal: true },
            { id: 'q1', label: 'q1', x: 40, y: 35, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q1', symbol: 'b' },
          ] } },
      { text: 'Solução: q2(final,loop c), q0â†’q2(c), q1â†’q2(c). "abc" e "cd" âœ“. PrÃ³ximas: "abcd", "ad", "bd", "d"!',
        boardDoneUpTo: 5, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 20, y: 65, isInitial: true, isFinal: true },
            { id: 'q1', label: 'q1', x: 40, y: 35, isInitial: false, isFinal: true },
            { id: 'q2', label: 'q2', x: 60, y: 65, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'c' },
            { from: 'q1', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q2', symbol: 'c' },
          ] } },
      { text: 'Foco em <b>abcd</b>, <b>ad</b>, <b>bd</b>, <b>d</b>: todos precisam do bloco d â€” q2 sem seta para "d"!',
        boardDoneUpTo: 5, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 20, y: 65, isInitial: true, isFinal: true },
            { id: 'q1', label: 'q1', x: 40, y: 35, isInitial: false, isFinal: true },
            { id: 'q2', label: 'q2', x: 60, y: 65, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'c' },
            { from: 'q1', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q2', symbol: 'c' },
          ] } },
      { text: 'Solução: q3(final,loop d) + atalhos q0â†’q3(d), q1â†’q3(d), q2â†’q3(d). Todos âœ“ ConcluÃ­do!',
        boardDoneUpTo: 9, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 20, y: 65, isInitial: true, isFinal: true },
            { id: 'q1', label: 'q1', x: 40, y: 35, isInitial: false, isFinal: true },
            { id: 'q2', label: 'q2', x: 60, y: 65, isInitial: false, isFinal: true },
            { id: 'q3', label: 'q3', x: 80, y: 35, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a' },
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'c' },
            { from: 'q0', to: 'q3', symbol: 'd' },
            { from: 'q1', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q2', symbol: 'c' },
            { from: 'q1', to: 'q3', symbol: 'd' },
            { from: 'q2', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q3', symbol: 'd' },
            { from: 'q3', to: 'q3', symbol: 'd' },
          ] } },
    ] },
  { id: 22, label: "L22", formula: "L = { w âˆˆ {0,1}* | w Ã© um nÃºmero par }",
    aliases: [
      "L = { w âˆˆ {0,1}* | w Ã© par }",
      "L = { w âˆˆ {0,1}* | w termina em 0 }",
      "L = { w âˆˆ {0,1}* | w termina com 0 }",
    ],
    desc: "",                                                                 shortestWord: "0",        regex: /^[01]*0$/,                                                  alphabet: ['0', '1'],             acceptedWords: ["0","10","110"],            rejectedWords: ["1","11","101"],        hint: "Pense em binÃ¡rio! Todo nÃºmero binÃ¡rio par termina com que dÃ­gito?",                                                 successMsg: "LÃ³gica binÃ¡ria! Terminou em zero.",
    tutorials: {
      onStart: { type: 'theory', title: 'Bem-vindo ao Mundo BinÃ¡rio!', dialog: [
        'Novo contexto: alfabeto {0, 1} â€” o sistema BINÃRIO!',
        'Em binÃ¡rio, todo nÃºmero PAR termina em "0". Todo ÃMPAR termina em "1". Simples!',
        'O AFD nÃ£o precisa ler a palavra inteira â€” sÃ³ o ÃšLTIMO sÃ­mbolo determina paridade.',
        'Isso implica: um estado "par" e um estado "Ã­mpar", trocando a cada sÃ­mbolo lido.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Dois Estados: Par e Ãmpar', dialog: [
        '2 estados: <b>q0</b>(inicial, Ãºltimo=1 ou vazio) e <b>q1</b>(Ãºltimo=0, FINAL).',
        '"0" de qualquer estado vai para <b>q1</b>. "1" de qualquer estado volta para <b>q0</b>.',
        'O AFD guarda sÃ³ o ÃšLTIMO bit. Loops em q0(1) e q1(0) cobrem sequÃªncias longas.',
      ] },
    },
    boardWords: ['0', '10', '110'],
    guidedLesson: [
      { text: 'PAR em binÃ¡rio termina em "0"!<br/>Aceitar: <b>0</b>, <b>10</b>, <b>110</b>. Rejeitar: 1, 11, 101.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>0</b>: menor caso â€” o Ãºltimo sÃ­mbolo Ã© "0". Preciso de q0â†’q1(0,final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1(final). "0" âœ“. PrÃ³ximas: "10" e "110"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 50, isInitial: true, isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [{ from: 'q0', to: 'q1', symbol: '0' }] } },
      { text: 'Foco em <b>10</b> e <b>110</b>: q0 lÃª "1" â€” sem seta! Precisam de loop q0(1) + loop q1(0) + q1â†’q0(1).',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 50, isInitial: true, isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [{ from: 'q0', to: 'q1', symbol: '0' }] } },
      { text: 'Solução: q0 loop 1, q1 loop 0, q1â†’q0(1). "10"=q0â†’q0â†’q1âœ“, "110"=q0â†’q0â†’q0â†’q1âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 50, isInitial: true, isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q0', to: 'q0', symbol: '1' },
            { from: 'q1', to: 'q1', symbol: '0' },
            { from: 'q1', to: 'q0', symbol: '1' },
          ] } },
    ] },
  { id: 23, label: "L23", formula: "L = { w âˆˆ {0,1}* | w Ã© um nÃºmero Ã­mpar }",
    aliases: [
      "L = { w âˆˆ {0,1}* | w Ã© Ã­mpar }",
      "L = { w âˆˆ {0,1}* | w termina em 1 }",
      "L = { w âˆˆ {0,1}* | w termina com 1 }",
    ],
    desc: "",                                                                 shortestWord: "1",        regex: /^[01]*1$/,                                                  alphabet: ['0', '1'],             acceptedWords: ["1","11","101"],            rejectedWords: ["0","10","100"],        hint: "NÃºmeros Ã­mpares em binÃ¡rio sempre terminam com '1'.",                                                               successMsg: "LÃ³gica binÃ¡ria! Terminou em um.",
    tutorials: {
      onStart: { type: 'theory', title: 'ÃMPAR em BinÃ¡rio Termina em "1"!', dialog: [
        'Espelho de L22: nÃºmero binÃ¡rio ÃMPAR termina em "1". PAR termina em "0".',
        '"1", "11", "101" â€” vÃ¡lidos. "0", "10" â€” invÃ¡lidos (terminam em 0).',
        'O AFD sÃ³ precisa lembrar o ÃšLTIMO dÃ­gito lido para decidir.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Dois Estados Espelhados', dialog: [
        '2 estados: <b>q0</b>(inicial, Ãºltimo=0 ou vazio) e <b>q1</b>(Ãºltimo=1, FINAL).',
        '"1" de qualquer estado vai para <b>q1</b>. "0" de qualquer estado volta para <b>q0</b>.',
        'Espelho do L22: loop q0(0) e q1(1). SÃ³ o ÃšLTIMO bit decide. "101": q0â†’q1â†’q0â†’q1 âœ”',
      ] },
    },
    boardWords: ['1', '01', '11', '101'],
    guidedLesson: [
      { text: 'ÃMPAR em binÃ¡rio termina em "1"!<br/>Aceitar: <b>1</b>, <b>01</b>, <b>11</b>, <b>101</b>. Rejeitar: 0, 10, 100.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>1</b>: menor caso â€” q0â†’q1(1,final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1(final). "1" âœ“. PrÃ³xima: "01"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 50, isInitial: true, isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [{ from: 'q0', to: 'q1', symbol: '1' }] } },
      { text: 'Foco em <b>01</b>: q0 lÃª "0" â€” sem seta! Preciso de loop q0(0).',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 50, isInitial: true, isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [{ from: 'q0', to: 'q1', symbol: '1' }] } },
      { text: 'Solução: q0 loop 0. "01"=q0â†’q0â†’q1âœ“. PrÃ³xima: "11"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 50, isInitial: true, isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q0', to: 'q0', symbol: '0' },
          ] } },
      { text: 'Foco em <b>11</b>: q1 lÃª 2Â° "1" â€” sem seta! Preciso de loop q1(1).',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 50, isInitial: true, isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q0', to: 'q0', symbol: '0' },
          ] } },
      { text: 'Solução: q1 loop 1. "11"=q0â†’q1â†’q1âœ“. PrÃ³xima: "101"!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 50, isInitial: true, isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q0', to: 'q0', symbol: '0' },
            { from: 'q1', to: 'q1', symbol: '1' },
          ] } },
      { text: 'Foco em <b>101</b>: q1 lÃª "0" â€” sem seta! Preciso de q1â†’q0(0).',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 50, isInitial: true, isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q0', to: 'q0', symbol: '0' },
            { from: 'q1', to: 'q1', symbol: '1' },
          ] } },
      { text: 'Solução: q1â†’q0(0). "101"=q0â†’q1â†’q0â†’q1âœ“ ConcluÃ­do!',
        boardDoneUpTo: 4, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 50, isInitial: true, isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q0', to: 'q0', symbol: '0' },
            { from: 'q1', to: 'q1', symbol: '1' },
            { from: 'q1', to: 'q0', symbol: '0' },
          ] } },
    ] },
  { id: 24, label: "L24", formula: "L = { w âˆˆ {0,1}* | w tem tamanho 3 }",                              desc: "",                                                                 shortestWord: "000",      regex: /^[01]{3}$/,                                                 alphabet: ['0', '1'],             acceptedWords: ["000","011","101"],         rejectedWords: ["Î»","00","0000"],       hint: "VocÃª precisa de um caminho reto que sÃ³ aceita na terceira etapa.",                                                  successMsg: "Controle de tamanho exato.",
    tutorials: {
      onStart: { type: 'theory', title: 'Caminho de Comprimento Exato!', dialog: [
        'L24: aceitar APENAS palavras com exatamente 3 sÃ­mbolos â€” nem mais, nem menos.',
        '"000", "101", "010" â€” vÃ¡lidas. "00" (curto), "0000" (longo) â€” invÃ¡lidas.',
        'EstratÃ©gia: 4 estados em linha â€” um por posiÃ§Ã£o lida. SÃ³ o 4Â° Ã© final.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Trilho de 3 Passos', dialog: [
        'Trilho linear: <b>q0</b>â†’<b>q1</b>â†’<b>q2</b>â†’<b>q3</b>(final). Cada seta aceita {0,1}.',
        'ApÃ³s q3, nÃ£o hÃ¡ transiÃ§Ãµes â€” qualquer sÃ­mbolo extra vai para o dead-state implÃ­cito.',
        '"0000": lÃª 4Â° sÃ­mbolo em q3, sem seta â†’ rejeiÃ§Ã£o automÃ¡tica. Sem estado extra!',
      ] },
    },
    boardWords: ['000', '101'],
    guidedLesson: [
      { text: 'Exatamente 3 sÃ­mbolos!<br/>Aceitar: <b>000</b>, <b>101</b>. Rejeitar: Î», 00, 0000.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>000</b> e <b>101</b>: ambas tÃªm 3 sÃ­mbolos â€” um trilho de 4 estados resolve as duas!',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1â†’q2â†’q3(final) com {0,1}. "000" e "101" âœ“. E "0000"?',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 50, isInitial: true, isFinal: false },
            { id: 'q1', label: 'q1', x: 40, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 65, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 85, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0,1' },
            { from: 'q1', to: 'q2', symbol: '0,1' },
            { from: 'q2', to: 'q3', symbol: '0,1' },
          ] } },
      { text: '"0000": q3 lÃª o 4Â° sÃ­mbolo â€” sem seta = dead-state implÃ­cito! Sem estado extra necessÃ¡rio. ConcluÃ­do!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 50, isInitial: true, isFinal: false },
            { id: 'q1', label: 'q1', x: 40, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 65, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 85, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0,1' },
            { from: 'q1', to: 'q2', symbol: '0,1' },
            { from: 'q2', to: 'q3', symbol: '0,1' },
          ] } },
    ] },
  { id: 25, label: "L25", formula: "L = { w âˆˆ {0,1}* | w tem tamanho menor que 3 }",                   desc: "",                                                                 shortestWord: "",         regex: /^[01]{0,2}$/,                                               alphabet: ['0', '1'],             acceptedWords: ["Î»","0","10"],             rejectedWords: ["000","0000","010"],    hint: "Os estados iniciais jÃ¡ podem ser finais, mas pare no terceiro passo.",                                               successMsg: "Tamanho mÃ¡ximo controlado.",
    tutorials: {
      onStart: { type: 'theory', title: 'Comprimento Menor que 3!', dialog: [
        'L25: aceitar palavras com 0, 1 ou 2 sÃ­mbolos. Rejeitar com 3 ou mais.',
        '"Î»", "0", "10" â€” vÃ¡lidas. "000", "0000" â€” invÃ¡lidas (longas demais).',
        'EstratÃ©gia: 3 estados finais (q0, q1, q2). ApÃ³s q2, sem transiÃ§Ãµes â€” dead-state implÃ­cito.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Trilho Curto com Dead-State ImplÃ­cito', dialog: [
        '<b>q0</b>(ini,f), <b>q1</b>(f), <b>q2</b>(f) â€” todos finais, aceita em qualquer um.',
        'q0â†’q1â†’q2 com {0,1}. ApÃ³s q2, sem transiÃ§Ãµes â€” 3Â° sÃ­mbolo dispara dead-state implÃ­cito.',
        'Dual de L24: aqui o trilho curto aceita, e a ausÃªncia de setas rejeita o extra.',
      ] },
    },
    boardWords: ['Î»', '0', '10'],
    guidedLesson: [
      { text: 'Comprimento 0, 1 ou 2!<br/>Aceitar: <b>Î»</b>, <b>0</b>, <b>10</b>. Rejeitar: 000, 0000.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>Î»</b>, <b>0</b> e <b>10</b>: trilho curto q0(f)â†’q1(f)â†’q2(f) resolve as trÃªs de vez!',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0(ini,f)â†’q1(f)â†’q2(f) com {0,1}. Î»=q0âœ“, "0"=q0â†’q1âœ“, "10"=q0â†’q1â†’q2âœ“. E "000"?',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 20, y: 50, isInitial: true, isFinal: true },
            { id: 'q1', label: 'q1', x: 50, y: 50, isInitial: false, isFinal: true },
            { id: 'q2', label: 'q2', x: 80, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0,1' },
            { from: 'q1', to: 'q2', symbol: '0,1' },
          ] } },
      { text: '"000": q2 lÃª o 3Â° sÃ­mbolo â€” sem seta = dead-state implÃ­cito! Sem qD necessÃ¡rio. ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 20, y: 50, isInitial: true, isFinal: true },
            { id: 'q1', label: 'q1', x: 50, y: 50, isInitial: false, isFinal: true },
            { id: 'q2', label: 'q2', x: 80, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0,1' },
            { from: 'q1', to: 'q2', symbol: '0,1' },
          ] } },
    ] },
  { id: 26, label: "L26", formula: "L = { w âˆˆ {0,1}* | w tem tamanho maior que 3 }",                   desc: "",                                                                 shortestWord: "0000",     regex: /^[01]{4,}$/,                                                alphabet: ['0', '1'],             acceptedWords: ["0000","1111","01010"],    rejectedWords: ["Î»","0","000"],         hint: "Passe pelos primeiros trÃªs estados sem aceitar, depois aceite tudo.",                                                successMsg: "Tamanho mÃ­nimo garantido.",
    tutorials: {
      onStart: { type: 'theory', title: 'Tamanho MAIOR que 3!', dialog: [
        'L26: aceitar palavras com 4 ou MAIS sÃ­mbolos. Rejeitar qualquer coisa menor.',
        '"0000", "1111", "01010" â€” vÃ¡lidas. "Î»", "0", "000" â€” invÃ¡lidas (muito curtas).',
        'EstratÃ©gia: 4 estados nÃ£o-finais (q0-q3) formam uma barreira. SÃ³ q4 Ã© final.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Trilho de 4 Passos + Loop', dialog: [
        'Trilho: <b>q0</b>(ini)â†’<b>q1</b>â†’<b>q2</b>â†’<b>q3</b>â†’<b>q4</b>(final) com {0,1}.',
        'ApÃ³s q4, loop <b>q4â†’q4</b> aceita palavras mais longas. Sem ele, "00000" travaria!',
        '"000" termina em q3 (nÃ£o final) â†’ rejeiÃ§Ã£o automÃ¡tica. PosiÃ§Ã£o importa, nÃ£o conteÃºdo.',
      ] },
    },
    boardWords: ['0000', '1111', '01010'],
    guidedLesson: [
      { text: 'MAIOR que 3 â€” mÃ­nimo 4 sÃ­mbolos!<br/>Aceitar: <b>0000</b>, <b>1111</b>, <b>01010</b>. Rejeitar: Î», 0, 000.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>0000</b> e <b>1111</b>: ambas tÃªm 4 sÃ­mbolos â€” trilho linear q0â†’â€¦â†’q4(final) resolve as duas!',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1â†’q2â†’q3â†’q4(final) com {0,1}. "0000"âœ“, "1111"âœ“. PrÃ³xima: "01010"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 65, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 65, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0,1' },
            { from: 'q1', to: 'q2', symbol: '0,1' },
            { from: 'q2', to: 'q3', symbol: '0,1' },
            { from: 'q3', to: 'q4', symbol: '0,1' },
          ] } },
      { text: 'Foco em <b>01010</b>: 5 sÃ­mbolos â€” q4 lÃª o 5Â° e trava! Preciso de loop q4(0,1).',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 65, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 65, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0,1' },
            { from: 'q1', to: 'q2', symbol: '0,1' },
            { from: 'q2', to: 'q3', symbol: '0,1' },
            { from: 'q3', to: 'q4', symbol: '0,1' },
          ] } },
      { text: 'Solução: q4 loop {0,1}. "01010"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 65, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 65, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0,1' },
            { from: 'q1', to: 'q2', symbol: '0,1' },
            { from: 'q2', to: 'q3', symbol: '0,1' },
            { from: 'q3', to: 'q4', symbol: '0,1' },
            { from: 'q4', to: 'q4', symbol: '0,1' },
          ] } },
    ] },
  { id: 27, label: "L27", formula: "L = { w âˆˆ {0,1}* | w tem tamanho mÃºltiplo de 3 }",                 desc: "",                                                                 shortestWord: "",         regex: /^([01]{3})*$/,                                              alphabet: ['0', '1'],             acceptedWords: ["Î»","000","010101"],       rejectedWords: ["0","00","0001"],       hint: "Crie um ciclo de 3 passos que volta para o estado final inicial.",                                                   successMsg: "Ciclo matemÃ¡tico de tamanho 3.",
    tutorials: {
      onStart: { type: 'theory', title: 'Contagem Modular â€” Mod 3!', dialog: [
        'MÃºltiplo de 3: comprimento â‰¡ 0 (mod 3). Ou seja, palavras de tamanho 0, 3, 6, 9...',
        'EstratÃ©gia: 3 estados formando um ciclo. Cada sÃ­mbolo avanÃ§a um passo no ciclo.',
        'q0 (final, mod 0) â†’(any)â†’ q1 (mod 1) â†’(any)â†’ q2 (mod 2) â†’(any)â†’ q0. Elegante!',
        'Esse padrÃ£o escala: para "mÃºltiplo de N", use N estados em ciclo.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Ciclo de 3 Estados', dialog: [
        '<b>q0</b>(ini,final) â†’ <b>q1</b> â†’ <b>q2</b> â†’ q0. Cada seta aceita {0,1}.',
        '"Î»" aceita em q0. "000": q0â†’q1â†’q2â†’q0 âœ”. "00": termina em q2 (nÃ£o final) âœ—.',
        '"0001" (4 sÃ­mbolos): q0â†’q1â†’q2â†’q0â†’q1 â†’ rejeitado em q1. O ciclo Ã© exato!',
      ] },
    },
    boardWords: ['Î»', '000', '010101'],
    guidedLesson: [
      { text: 'MÃºltiplo de 3 â€” comprimento â‰¡ 0 (mod 3)!<br/>Aceitar: <b>Î»</b>, <b>000</b>, <b>010101</b>. Rejeitar: 0, 00, 0001.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>Î»</b>: palavra vazia â€” q0(ini,final) aceita imediatamente!',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0(ini,final). "Î»"âœ“. PrÃ³ximas: "000" e "010101"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [{ id: 'q0', label: 'q0', x: 15, y: 68, isInitial: true, isFinal: true }],
          transitions: [] } },
      { text: 'Foco em <b>000</b> e <b>010101</b>: ambas tÃªm comprimento mÃºltiplo de 3 â€” ciclo q0â†’q1â†’q2â†’q0 resolve as duas!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [{ id: 'q0', label: 'q0', x: 15, y: 68, isInitial: true, isFinal: true }],
          transitions: [] } },
      { text: 'Solução: q0â†’q1â†’q2â†’q0(final) com {0,1}. Ciclo completo! "000"âœ“, "010101"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 68, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 50, y: 20, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 85, y: 68, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0,1' },
            { from: 'q1', to: 'q2', symbol: '0,1' },
            { from: 'q2', to: 'q0', symbol: '0,1' },
          ] } },
    ] },
  { id: 28, label: "L28", formula: "L = { w âˆˆ {0,1}* | cada 0 Ã© seguido de, no mÃ­nimo, dois 1's }",   desc: "",                                                                 shortestWord: "",         regex: /^(1*011+)*1*$/,                                             alphabet: ['0', '1'],             acceptedWords: ["Î»","011","1011"],         rejectedWords: ["0","01","010"],        hint: "Leu um '0'? EntÃ£o os prÃ³ximos dois passos OBRIGATORIAMENTE devem ser '1'.",                                         successMsg: "PadrÃ£o de seguranÃ§a estabelecido.",
    tutorials: {
      onStart: { type: 'theory', title: 'Cada 0 Exige Dois 1s!', dialog: [
        'RestriÃ§Ã£o: todo "0" lido OBRIGA que os prÃ³ximos dois sÃ­mbolos sejam "1".',
        '"Î»" e "1011" â€” vÃ¡lidos (1s livres; cada 0 seguido de "11"). "01" â€” invÃ¡lido (sÃ³ um 1).',
        'EstratÃ©gia: rastrear a "dÃ­vida" â€” quantos 1s ainda devemos apÃ³s o Ãºltimo 0.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Estados de DÃ­vida', dialog: [
        '<b>q0</b>(ini,f): sem dÃ­vida. <b>q1</b>: deve 2 uns. <b>q2</b>: deve 1 un. <b>qT</b>: dead.',
        '1 em q0: loop. 0 em q0: gera dÃ­vida (â†’q1). 1 em q1: paga parcial (â†’q2). 1 em q2: quita (â†’q0).',
        'Novo 0 antes de quitar (q1â†’qT ou q2â†’qT) = violaÃ§Ã£o irrecuperÃ¡vel. qT rejeita tudo.',
      ] },
    },
    boardWords: ['011', '1011'],
    guidedLesson: [
      { text: 'Todo "0" exige dois "1"s em seguida!<br/>Aceitar: <b>Î»</b>, <b>011</b>, <b>1011</b>. Rejeitar: 0, 01, 010.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>011</b>: menor palavra com "0" â€” q0â†’q1(0)â†’q2(1)â†’q0(1), dÃ­vida quitada!',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0(ini,f)â†’q1(0)â†’q2(1)â†’q0(1). "011"âœ“. PrÃ³xima: "1011"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 35, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 50, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 85, y: 35, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q1', to: 'q2', symbol: '1' },
            { from: 'q2', to: 'q0', symbol: '1' },
          ] } },
      { text: 'Foco em <b>1011</b>: q0 lÃª "1" â€” sem seta! Preciso de loop q0(1).',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 35, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 50, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 85, y: 35, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q1', to: 'q2', symbol: '1' },
            { from: 'q2', to: 'q0', symbol: '1' },
          ] } },
      { text: 'Solução: q0 loop 1. "1011"=q0â†’q0â†’q1â†’q2â†’q0âœ“. q1â€”0 e q2â€”0 sem seta = dead implÃ­cito. ConcluÃ­do!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 35, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 50, y: 70, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 85, y: 35, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: '1' },
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q1', to: 'q2', symbol: '1' },
            { from: 'q2', to: 'q0', symbol: '1' },
          ] } },
    ] },
  { id: 29, label: "L29", formula: "L = { w âˆˆ {0,1}* | os primeiros 4 sÃ­mbolos de w contÃªm, no mÃ­nimo, dois 1's }", desc: "", shortestWord: "11", regex: /^([01]*)$/, validate: w => w.slice(0,4).split('').filter(c=>c==='1').length >= 2, alphabet: ['0', '1'], acceptedWords: ["11","0011","1011"],      rejectedWords: ["0","00","0001"],       hint: "Essa exige rastrear o prefixo. Concentre-se nas combinaÃ§Ãµes dos primeiros passos.",                                  successMsg: "Prefixo complexo analisado.",
    tutorials: {
      onStart: { type: 'theory', title: 'Rastreando o Prefixo de 4!', dialog: [
        'L29: os 4 primeiros sÃ­mbolos devem conter ao menos 2 uns. O resto Ã© livre.',
        '"0011": prefixo "0011" tem 2 uns âœ”. "0001": prefixo "0001" tem 1 um âœ—.',
        'EstratÃ©gia: 9 estados rastreiam (posiÃ§Ã£o, uns vistos) para posiÃ§Ãµes 1-4.',
        'ApÃ³s 4 sÃ­mbolos com â‰¥2 uns, q6 aceita tudo via loop. Dead-states implÃ­citos para caminhos impossÃ­veis.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Ãrvore de Prefixo 4Ã—2', dialog: [
        'Camada 1: q0â€”0â†’q1(0 uns), q0â€”1â†’q2(1 um). Camada 2: q1,q2 expandem para q3,q4,q7.',
        'Camada 3: q3,q4,q7 expandem para q5,q8. Camada 4: q5,q8â€”{0,1}â†’q6(final, loop).',
        'q3â€”0â†’dead (impossÃ­vel: 3 zeros, sÃ³ 1 posiÃ§Ã£o restante). q5â€”0â†’dead (4 sÃ­mbolos, sÃ³ 1 um).',
      ] },
    },
    boardWords: ['11', '0011', '1011'],
    guidedLesson: [
      { text: '4 primeiros sÃ­mbolos com â‰¥ 2 uns!<br/>Aceitar: <b>11</b>, <b>0011</b>, <b>1011</b>. Rejeitar: 0, 00, 0001.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>11</b>: apenas 2 sÃ­mbolos â€” q0â†’q2(1)â†’q7(1,final) com 3 estados!',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q2(1)â†’q7(final,1). "11"=q0â†’q2â†’q7âœ“. PrÃ³ximas: "0011" e "1011"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 50, y: 10, isInitial: true,  isFinal: false },
            { id: 'q2', label: 'q2', x: 75, y: 33, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 87, y: 58, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q2', symbol: '1' },
            { from: 'q2', to: 'q7', symbol: '1' },
          ] } },
      { text: 'Foco em <b>0011</b> e <b>1011</b>: 4 sÃ­mbolos â€” precisam da Ã¡rvore completa de prefixo!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 50, y: 10, isInitial: true,  isFinal: false },
            { id: 'q2', label: 'q2', x: 75, y: 33, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 87, y: 58, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q2', symbol: '1' },
            { from: 'q2', to: 'q7', symbol: '1' },
          ] } },
      { text: 'Solução: Ã¡rvore de prefixo 4Ã—2 completa. q7,q8,q6 finais. "0011"=q0â†’q1â†’q3â†’q5â†’q6âœ“, "1011"=q0â†’q2â†’q4â†’q8âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 50, y: 10, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 25, y: 33, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 75, y: 33, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 10, y: 58, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 50, y: 58, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 87, y: 58, isInitial: false, isFinal: true  },
            { id: 'q5', label: 'q5', x: 30, y: 78, isInitial: false, isFinal: false },
            { id: 'q8', label: 'q8', x: 70, y: 78, isInitial: false, isFinal: true  },
            { id: 'q6', label: 'q6', x: 50, y: 93, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q0', to: 'q2', symbol: '1' },
            { from: 'q1', to: 'q3', symbol: '0' },
            { from: 'q1', to: 'q4', symbol: '1' },
            { from: 'q2', to: 'q4', symbol: '0' },
            { from: 'q2', to: 'q7', symbol: '1' },
            { from: 'q3', to: 'q5', symbol: '1' },
            { from: 'q4', to: 'q5', symbol: '0' },
            { from: 'q4', to: 'q8', symbol: '1' },
            { from: 'q7', to: 'q8', symbol: '0,1' },
            { from: 'q5', to: 'q6', symbol: '1' },
            { from: 'q8', to: 'q6', symbol: '0,1' },
            { from: 'q6', to: 'q6', symbol: '0,1' },
          ] } },
    ] },
  { id: 30, label: "L30", formula: "L = { w âˆˆ {0,1}* | w NÃƒO contÃ©m 000 nem 111 }",                    desc: "",                                                                 shortestWord: "",         regex: /^(?!.*000)(?!.*111)[01]*$/,                                 alphabet: ['0', '1'],             acceptedWords: ["Î»","01","0101"],          rejectedWords: ["000","111","1000"],    hint: "Se 3 zeros ou 3 uns aparecerem, jogue a palavra num estado de erro.",                                                successMsg: "Evitou a bomba tripla!",
    tutorials: {
      onStart: { type: 'theory', title: 'Evitando Subpalavras Proibidas!', dialog: [
        'Novo padrÃ£o: NÃƒO CONTÃ‰M â€” rejeitar quando uma sequÃªncia especÃ­fica aparecer.',
        'EstratÃ©gia: rastrear o "progresso" da sequÃªncia proibida com estados intermediÃ¡rios.',
        '"0" visto â†’ alerta. "00" visto â†’ alerta mÃ¡ximo. "000" visto â†’ ARMADILHA irrecuperÃ¡vel!',
        'SÃ£o duas sequÃªncias proibidas independentes (000 e 111), cada uma com sua trilha de estados.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Duas Trilhas, Dois Limites', dialog: [
        '5 estados todos finais: <b>q0</b>(ini), <b>q1</b>(um 0), <b>q2</b>(dois 0s), <b>q3</b>(um 1), <b>q4</b>(dois 1s).',
        'Cruzamentos: q1â€”1â†’q3 e q3â€”0â†’q1 (troca de corrida cancela a contagem anterior).',
        'Dead implÃ­cito: q2 lÃª 0 = terceiro zero = 000. q4 lÃª 1 = terceiro um = 111. Sem seta = rejeitado!',
      ] },
    },
    boardWords: ['Î»', '01', '0101'],
    guidedLesson: [
      { text: 'Proibido 000 e proibido 111!<br/>Aceitar: <b>Î»</b>, <b>01</b>, <b>0101</b>. Rejeitar: 000, 111, 1000.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>Î»</b> e <b>01</b>: Î»=q0(f), "01"=q0â†’q1(0)â†’q3(1,f). 4 transiÃ§Ãµes bÃ¡sicas resolvem as duas!',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0(f)â†’q1(f)(0)â†’q3(f)(1)â†’q1(0); q0â†’q3(1). "Î»"âœ“, "01"âœ“. PrÃ³xima: "0101"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: true },
            { id: 'q1', label: 'q1', x: 48, y: 20, isInitial: false, isFinal: true },
            { id: 'q3', label: 'q3', x: 48, y: 80, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q0', to: 'q3', symbol: '1' },
            { from: 'q1', to: 'q3', symbol: '1' },
            { from: 'q3', to: 'q1', symbol: '0' },
          ] } },
      { text: 'Foco em <b>0101</b>: q1 lÃª 2Â° "0" â€” sem seta! E q3 lÃª 2Â° "1" â€” sem seta!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: true },
            { id: 'q1', label: 'q1', x: 48, y: 20, isInitial: false, isFinal: true },
            { id: 'q3', label: 'q3', x: 48, y: 80, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q0', to: 'q3', symbol: '1' },
            { from: 'q1', to: 'q3', symbol: '1' },
            { from: 'q3', to: 'q1', symbol: '0' },
          ] } },
      { text: 'Solução: q1â†’q2(0)â†’q3(1) e q3â†’q4(1)â†’q1(0). Dead implÃ­cito: q2â€”0=000, q4â€”1=111. "0101"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: true },
            { id: 'q1', label: 'q1', x: 48, y: 20, isInitial: false, isFinal: true },
            { id: 'q2', label: 'q2', x: 85, y: 20, isInitial: false, isFinal: true },
            { id: 'q3', label: 'q3', x: 48, y: 80, isInitial: false, isFinal: true },
            { id: 'q4', label: 'q4', x: 12, y: 80, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q0', to: 'q3', symbol: '1' },
            { from: 'q1', to: 'q2', symbol: '0' },
            { from: 'q1', to: 'q3', symbol: '1' },
            { from: 'q2', to: 'q3', symbol: '1' },
            { from: 'q3', to: 'q1', symbol: '0' },
            { from: 'q3', to: 'q4', symbol: '1' },
            { from: 'q4', to: 'q1', symbol: '0' },
          ] } },
    ] },
  { id: 31, label: "L31", formula: "L = { w âˆˆ {0,1}* | os Ãºltimos trÃªs sÃ­mbolos de w NÃƒO sÃ£o 000 }",  desc: "",                                                                 shortestWord: "",         regex: /^(?!.*000$)[01]*$/,                                         alphabet: ['0', '1'],             acceptedWords: ["Î»","1","001"],            rejectedWords: ["000","1000","10000"],  hint: "O final da palavra Ã© o mais importante aqui.",                                                                      successMsg: "Sufixo validado.",
    tutorials: {
      onStart: { type: 'theory', title: 'Sufixo Proibido: "000"!', dialog: [
        'Diferente de L30, L31 sÃ³ proÃ­be "000" como SUFIXO â€” nÃ£o em qualquer posiÃ§Ã£o.',
        '"1000" Ã© rejeitado (termina em 000). "0001" Ã© ACEITO (nÃ£o termina em 000)!',
        'EstratÃ©gia: rastrear os Ãºltimos 3 sÃ­mbolos. Se forem "000", entrar em estado especial.',
        'Um "1" depois de "000" RESETA o sufixo â€” o autÃ´mato Ã© escapÃ¡vel!',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Trilho ReversÃ­vel de 4 Estados', dialog: [
        '<b>q0</b>(ini,f): sufixo OK. <b>q1</b>(f): Ãºltimo=0. <b>q2</b>(f): Ãºltimos=00. <b>q3</b>: Ãºltimos=000.',
        '"1" em qualquer estado â†’ q0 (sufixo "1" nÃ£o ameaÃ§a). "0" avanÃ§a a trilha.',
        'q3 nÃ£o Ã© final (000 no sufixo). Mas q3â€”1â†’q0 permite escapar! "10001": termina em "001" â†’ aceito.',
      ] },
    },
    boardWords: ['Î»', '1', '001'],
    guidedLesson: [
      { text: 'Sufixo "000" proibido â€” mas escapÃ¡vel com "1"!<br/>Aceitar: <b>Î»</b>, <b>1</b>, <b>001</b>. Rejeitar: 000, 1000, 10000.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>Î»</b>, <b>1</b> e <b>001</b>: todas resolvidas pela mesma estrutura de 3 estados!',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0(f) loop 1, q0â†’q1(0)â†’q2(0)â†’q0(1). "Î»"âœ“, "1"âœ“, "001"âœ“. E "000"?',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 50, isInitial: true,  isFinal: true },
            { id: 'q1', label: 'q1', x: 42, y: 25, isInitial: false, isFinal: true },
            { id: 'q2', label: 'q2', x: 68, y: 50, isInitial: false, isFinal: true },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: '1' },
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q1', to: 'q2', symbol: '0' },
            { from: 'q1', to: 'q0', symbol: '1' },
            { from: 'q2', to: 'q0', symbol: '1' },
          ] } },
      { text: '"000": q2 lÃª 3Â° zero â€” sem seta! Solução: q2â†’q3(0,nÃ£o-final), q3 loop 0, q3â†’q0(1,escape). ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 50, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 42, y: 25, isInitial: false, isFinal: true  },
            { id: 'q2', label: 'q2', x: 68, y: 50, isInitial: false, isFinal: true  },
            { id: 'q3', label: 'q3', x: 88, y: 25, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: '1' },
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q1', to: 'q2', symbol: '0' },
            { from: 'q1', to: 'q0', symbol: '1' },
            { from: 'q2', to: 'q3', symbol: '0' },
            { from: 'q2', to: 'q0', symbol: '1' },
            { from: 'q3', to: 'q3', symbol: '0' },
            { from: 'q3', to: 'q0', symbol: '1' },
          ] } },
    ] },
  { id: 32, label: "L32", formula: "L = { w âˆˆ {0,1,2}* | par de 0's, par de 1's e par de 2's }",      desc: "",                                                                 shortestWord: "",         regex: /^.*$/, validate: w => ['0','1','2'].every(c => [...w].filter(x=>x===c).length%2===0), alphabet: ['0', '1', '2'],        acceptedWords: ["Î»","0011","001122"],      rejectedWords: ["0","1","012"],         hint: "Paridade tripla! Vai precisar de estados para todas as combinaÃ§Ãµes de par/Ã­mpar.",                                  successMsg: "AutÃ´mato massivo concluÃ­do.",
    tutorials: {
      onStart: { type: 'theory', title: 'ExplosÃ£o de Estados â€” 2Â³ = 8!', dialog: [
        'Paridade tripla simultÃ¢nea: par/Ã­mpar de 0s, de 1s e de 2s â€” totalmente independentes.',
        'Cada combinaÃ§Ã£o possÃ­vel exige seu prÃ³prio estado: 2Â³ = 8 estados no total!',
        'SÃ³ o estado (par-0, par-1, par-2) Ã© final. Os outros 7 sÃ£o nÃ£o-finais.',
        'PrincÃ­pio geral: N paridades independentes â†’ 2^N estados no AFD mÃ­nimo.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Cubo de Paridade 3D', dialog: [
        'Cada estado = vetor (par_0, par_1, par_2). q0=(0,0,0) Ã© o Ãºnico final.',
        'Ler 0 inverte bit-0, ler 1 inverte bit-1, ler 2 inverte bit-2.',
        'O autÃ´mato forma um cubo: 8 vÃ©rtices, cada aresta troca exatamente um bit.',
      ] },
    },
    boardWords: ['Î»', '0011', '001122'],
    guidedLesson: [
      { text: 'Paridade tripla: par de 0s AND par de 1s AND par de 2s!<br/>Aceitar: <b>Î»</b>, <b>0011</b>, <b>001122</b>. Rejeitar: 0, 1, 012.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>Î»</b> e <b>0011</b>: paridades de 0 e 1 â€” 4 estados resolvem as duas!',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0(f)â†”q1 via 0; q0â†”q2 via 1; q1â†”q4 via 1; q2â†”q4 via 0. "Î»"âœ“, "0011"âœ“. PrÃ³xima: "001122"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 50, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 42, y: 25, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 42, y: 75, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 68, y: 50, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q1', to: 'q0', symbol: '0' },
            { from: 'q0', to: 'q2', symbol: '1' },
            { from: 'q2', to: 'q0', symbol: '1' },
            { from: 'q1', to: 'q4', symbol: '1' },
            { from: 'q4', to: 'q1', symbol: '1' },
            { from: 'q2', to: 'q4', symbol: '0' },
            { from: 'q4', to: 'q2', symbol: '0' },
          ] } },
      { text: 'Foco em <b>001122</b>: contÃ©m "2" â€” sem seta para 2 no grafo atual!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 50, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 42, y: 25, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 42, y: 75, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 68, y: 50, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q1', to: 'q0', symbol: '0' },
            { from: 'q0', to: 'q2', symbol: '1' },
            { from: 'q2', to: 'q0', symbol: '1' },
            { from: 'q1', to: 'q4', symbol: '1' },
            { from: 'q4', to: 'q1', symbol: '1' },
            { from: 'q2', to: 'q4', symbol: '0' },
            { from: 'q4', to: 'q2', symbol: '0' },
          ] } },
      { text: 'Solução: cubo de paridade â€” 4 novos estados q3,q5,q6,q7 via sÃ­mbolo 2. "001122"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3,
        stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 12, y: 50, isInitial: true,  isFinal: true  },
            { id: 'q1', label: 'q1', x: 35, y: 22, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 35, y: 78, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 57, y: 50, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 58, y: 22, isInitial: false, isFinal: false },
            { id: 'q5', label: 'q5', x: 78, y: 22, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 78, y: 78, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 90, y: 50, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q1', to: 'q0', symbol: '0' },
            { from: 'q0', to: 'q2', symbol: '1' },
            { from: 'q2', to: 'q0', symbol: '1' },
            { from: 'q0', to: 'q3', symbol: '2' },
            { from: 'q3', to: 'q0', symbol: '2' },
            { from: 'q1', to: 'q4', symbol: '1' },
            { from: 'q4', to: 'q1', symbol: '1' },
            { from: 'q1', to: 'q5', symbol: '2' },
            { from: 'q5', to: 'q1', symbol: '2' },
            { from: 'q2', to: 'q4', symbol: '0' },
            { from: 'q4', to: 'q2', symbol: '0' },
            { from: 'q2', to: 'q6', symbol: '2' },
            { from: 'q6', to: 'q2', symbol: '2' },
            { from: 'q3', to: 'q5', symbol: '0' },
            { from: 'q5', to: 'q3', symbol: '0' },
            { from: 'q3', to: 'q6', symbol: '1' },
            { from: 'q6', to: 'q3', symbol: '1' },
            { from: 'q4', to: 'q7', symbol: '2' },
            { from: 'q7', to: 'q4', symbol: '2' },
            { from: 'q5', to: 'q7', symbol: '1' },
            { from: 'q7', to: 'q5', symbol: '1' },
            { from: 'q6', to: 'q7', symbol: '0' },
            { from: 'q7', to: 'q6', symbol: '0' },
          ],
        } },
    ] },
  { id: 33, label: "L33", formula: "L = { w âˆˆ {0,1}* | w tem 001 como prefixo }",                      desc: "",                                                                 shortestWord: "001",      regex: /^001[01]*$/,                                                alphabet: ['0', '1'],             acceptedWords: ["001","0011","001100"],    rejectedWords: ["Î»","1","010"],         hint: "O comeÃ§o tem que ser rigorosamente '0' -> '0' -> '1'.",                                                             successMsg: "Prefixo amarrado!",
    tutorials: {
      onStart: { type: 'theory', title: 'Prefixo ObrigatÃ³rio: "001"!', dialog: [
        'L33: toda palavra aceita DEVE comeÃ§ar com "001". O resto pode ser qualquer coisa.',
        '"001100" â€” vÃ¡lida (comeÃ§a com 001). "010" â€” invÃ¡lida (2Â° sÃ­mbolo Ã© 1, nÃ£o 0).',
        'EstratÃ©gia: 3 estados de checagem (q0â†’q1â†’q2) + estado final q3 com loop.',
        'Qualquer desvio no prefixo cai em dead-state implÃ­cito. Sem volta!',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Trilho de Prefixo + Loop Final', dialog: [
        'q0â€”0â†’q1â€”0â†’q2â€”1â†’q3(final). Cadeia linear exata para "001".',
        'q3â€”{0,1}â†’q3: apÃ³s confirmar o prefixo, qualquer sÃ­mbolo Ã© aceito.',
        'Dead implÃ­cito: q0â€”1, q1â€”1, q2â€”0 â€” qualquer desvio rejeita permanentemente.',
      ] },
    },
    boardWords: ['001'],
    guidedLesson: [
      { text: 'Prefixo obrigatÃ³rio "001"!<br/>Aceitar: <b>001</b>, <b>0011</b>, <b>001100</b>. Rejeitar: Î», 1, 010.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>001</b>: prefixo exato "001" â€” trilho linear q0â†’q1(0)â†’q2(0)â†’q3(1,final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1(0)â†’q2(0)â†’q3(final,1). "001"=q0â†’q1â†’q2â†’q3âœ“. E "0011"?',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 40, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 65, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 88, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q1', to: 'q2', symbol: '0' },
            { from: 'q2', to: 'q3', symbol: '1' },
          ] } },
      { text: '"0011": q3 lÃª "1" â€” sem seta! Solução: q3 loop {0,1}. "001100": q3 absorve o resto. ConcluÃ­do!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 40, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 65, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 88, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '0' },
            { from: 'q1', to: 'q2', symbol: '0' },
            { from: 'q2', to: 'q3', symbol: '1' },
            { from: 'q3', to: 'q3', symbol: '0,1' },
          ] } },
    ] },
  { id: 34, label: "L34", formula: "L = { w âˆˆ {0,1}* | w tem 1010 como sufixo }",                      desc: "",                                                                 shortestWord: "1010",     regex: /^[01]*1010$/,                                               alphabet: ['0', '1'],             acceptedWords: ["1010","01010","001010"], rejectedWords: ["Î»","101","1011"],       hint: "Mantenha a porta aberta para infinitos caracteres, mas sÃ³ aceite se a 'memÃ³ria' bater com 1010.",                  successMsg: "Detector de sufixo ativado.",
    tutorials: {
      onStart: { type: 'theory', title: 'Detector de Sufixo "1010"!', dialog: [
        'L34: a palavra termina em "1010". O comeÃ§o pode ser qualquer coisa!',
        '"01010" â€” vÃ¡lida (termina em 1010). "1011" â€” invÃ¡lida (termina em 1011).',
        'EstratÃ©gia: 5 estados rastreiam o melhor sufixo que seja prefixo de "1010".',
        'Ao sair do padrÃ£o, backedges resetam para o estado correto â€” sem perder contexto.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Sufixo com Backedges', dialog: [
        'Cadeia: q0â€”1â†’q1â€”0â†’q2â€”1â†’q3â€”0â†’q4(final). LÃª "1010" perfeito!',
        'AbsorÃ§Ã£o: q0â€”0â†’q0 (0 antes de 1 nÃ£o ajuda). q1â€”1â†’q1 (dois 1s; sÃ³ o Ãºltimo conta).',
        'Resets: q2â€”0â†’q0, q3â€”1â†’q0, q4â€”0â†’q0. q4â€”1â†’q3 (apÃ³s "1010"+1 â†’ novo "101").',
      ] },
    },
    boardWords: ['1010', '01010', '001010'],
    guidedLesson: [
      { text: 'Sufixo obrigatÃ³rio "1010"!<br/>Aceitar: <b>1010</b>, <b>01010</b>, <b>001010</b>. Rejeitar: Î», 101, 1011.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>1010</b>: cadeia q0â†’q1(1)â†’q2(0)â†’q3(1)â†’q4(0,final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1(1)â†’q2(0)â†’q3(1)â†’q4(final,0). "1010"âœ“. PrÃ³ximas: "01010" e "001010"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 65, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 65, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q1', to: 'q2', symbol: '0' },
            { from: 'q2', to: 'q3', symbol: '1' },
            { from: 'q3', to: 'q4', symbol: '0' },
          ] } },
      { text: 'Foco em <b>01010</b> e <b>001010</b>: q0 lÃª "0" â€” sem seta! Preciso de loops e resets.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 65, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 65, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q1', to: 'q2', symbol: '0' },
            { from: 'q2', to: 'q3', symbol: '1' },
            { from: 'q3', to: 'q4', symbol: '0' },
          ] } },
      { text: 'Solução: q0 loop 0, q1 loop 1, resets q2â†’q0(0), q3â†’q0(1), q4â†’q0(0), q4â†’q3(1). "01010"âœ“, "001010"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 65, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 65, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: '0' },
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q1', to: 'q1', symbol: '1' },
            { from: 'q1', to: 'q2', symbol: '0' },
            { from: 'q2', to: 'q0', symbol: '0' },
            { from: 'q2', to: 'q3', symbol: '1' },
            { from: 'q3', to: 'q4', symbol: '0' },
            { from: 'q3', to: 'q0', symbol: '1' },
            { from: 'q4', to: 'q0', symbol: '0' },
            { from: 'q4', to: 'q3', symbol: '1' },
          ] } },
    ] },
  { id: 35, label: "L35a", formula: "L = { w âˆˆ {0,1}* | w tem 1111 como subpalavra }",                 desc: "",                                                                 shortestWord: "1111",     regex: /^[01]*1111[01]*/,                                           alphabet: ['0', '1'],             acceptedWords: ["1111","01111","11110"],   rejectedWords: ["Î»","111","11011"],     hint: "Assim que achar quatro '1's seguidos, pode ir para um estado final que aceita tudo.",                               successMsg: "Achou a subpalavra!",
    tutorials: {
      onStart: { type: 'theory', title: 'CaÃ§ando "1111"!', dialog: [
        'L35a: a palavra CONTÃ‰M "1111" como subpalavra (em qualquer posiÃ§Ã£o).',
        '"01111" â€” vÃ¡lida (contÃ©m 1111). "11011" â€” invÃ¡lida (corrida de 1s interrompida).',
        'EstratÃ©gia: contar 1s consecutivos. Ao atingir 4, entrar em estado final permanente.',
        'Um "0" a qualquer momento zera a contagem e volta ao inÃ­cio.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Contador de Uns Consecutivos', dialog: [
        'q0: nenhum 1. q1: um 1. q2: dois 1s. q3: trÃªs 1s. q4(final): quatro ou mais 1s!',
        'Ler 0 em q0/q1/q2/q3 â†’ volta para q0 (zera contagem).',
        'q4â€”{0,1}â†’q4: uma vez achados os 4 uns, a palavra jÃ¡ Ã© vÃ¡lida. Loop eterno!',
      ] },
    },
    boardWords: ['1111'],
    guidedLesson: [
      { text: 'Subpalavra "1111" em qualquer posiÃ§Ã£o!<br/>Aceitar: <b>1111</b>, <b>01111</b>, <b>11110</b>. Rejeitar: Î», 111, 11011.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>1111</b>: cadeia de 5 estados, contador de uns consecutivos.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1(1)â†’q2(1)â†’q3(1)â†’q4(final,1). "1111"âœ“. E "01111"?',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 65, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 65, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q1', to: 'q2', symbol: '1' },
            { from: 'q2', to: 'q3', symbol: '1' },
            { from: 'q3', to: 'q4', symbol: '1' },
          ] } },
      { text: '"01111": q0 lÃª "0" â€” sem seta! Solução: resets q0-q3 com 0â†’q0, q4 loop {0,1}. "11110"âœ“, "11011"â†’q2âœ—. ConcluÃ­do!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 65, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 28, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 46, y: 65, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 64, y: 35, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 82, y: 65, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: '0' },
            { from: 'q0', to: 'q1', symbol: '1' },
            { from: 'q1', to: 'q0', symbol: '0' },
            { from: 'q1', to: 'q2', symbol: '1' },
            { from: 'q2', to: 'q0', symbol: '0' },
            { from: 'q2', to: 'q3', symbol: '1' },
            { from: 'q3', to: 'q0', symbol: '0' },
            { from: 'q3', to: 'q4', symbol: '1' },
            { from: 'q4', to: 'q4', symbol: '0,1' },
          ] } },
    ] },
  { id: 36, label: "L35b", formula: "L = { w âˆˆ {a,b,c,d}* | w tem abc como prefixo }",                 desc: "",                                                                 shortestWord: "abc",      regex: /^abc[abcd]*/,                                               alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["abc","abcd","abcabc"],   rejectedWords: ["Î»","ab","bca"],        hint: "Igual ao 001, mas com um alfabeto maior.",                                                                          successMsg: "Prefixo alfabÃ©tico concluÃ­do.",
    tutorials: {
      onStart: { type: 'theory', title: 'Prefixo ObrigatÃ³rio: "abc"!', dialog: [
        'L35b: toda palavra aceita DEVE comeÃ§ar com "abc". O resto pode ser qualquer coisa.',
        '"abcd" â€” vÃ¡lida (comeÃ§a com abc). "bca" â€” invÃ¡lida (1Â° sÃ­mbolo Ã© b, nÃ£o a).',
        'EstratÃ©gia: 3 estados de checagem (q0â†’q1â†’q2) + estado final q3 com loop.',
        'Qualquer desvio no prefixo cai em dead-state implÃ­cito. Sem volta!',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Trilho de Prefixo + Loop Final', dialog: [
        'q0â€”aâ†’q1â€”bâ†’q2â€”câ†’q3(final). Cadeia linear exata para "abc".',
        'q3â€”{a,b,c,d}â†’q3: apÃ³s confirmar o prefixo, qualquer sÃ­mbolo Ã© aceito.',
        'Dead implÃ­cito: q0â€”{b,c,d}, q1â€”{a,c,d}, q2â€”{a,b,d} â€” qualquer desvio rejeita permanentemente.',
      ] },
    },
    boardWords: ['abc', 'abcd', 'abcabc'],
    guidedLesson: [
      { text: 'Prefixo obrigatÃ³rio "abc"!<br/>Aceitar: <b>abc</b>, <b>abcd</b>, <b>abcabc</b>. Rejeitar: Î», ab, bca.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>abc</b>: prefixo exato â€” trilho q0â†’q1(a)â†’q2(b)â†’q3(c,final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1(a)â†’q2(b)â†’q3(final,c). "abc"âœ“. PrÃ³ximas: "abcd" e "abcabc"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 38, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 62, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 85, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
          ] } },
      { text: 'Foco em <b>abcd</b> e <b>abcabc</b>: q3 lÃª "d" ou "a" â€” sem seta! Preciso de loop q3.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 38, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 62, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 85, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
          ] } },
      { text: 'Solução: q3 loop {a,b,c,d}. "abcd"âœ“, "abcabc"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 15, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 38, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 62, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 85, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q3', symbol: 'a,b,c,d' },
          ] } },
    ] },
  { id: 37, label: "L36", formula: "L = { w âˆˆ {a,b,c,d}* | w tem dcba como sufixo }",                  desc: "",                                                                 shortestWord: "dcba",     regex: /^[abcd]*dcba$/,                                             alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["dcba","adcba","aadcba"], rejectedWords: ["Î»","dcb","abcd"],      hint: "O caminho final deve obrigatoriamente soletrar 'dcba'.",                                                            successMsg: "Sufixo alfabÃ©tico detectado.",
    tutorials: {
      onStart: { type: 'theory', title: 'Sufixo ObrigatÃ³rio: "dcba"!', dialog: [
        'L36: a palavra deve TERMINAR com "dcba". O prefixo pode ser qualquer coisa.',
        '"dcba" âœ“ "adcba" âœ“ "aadcba" âœ“. "Î»", "dcb", "abcd" âœ—.',
        'TÃ©cnica KMP: 5 estados rastreiam quanto do sufixo "dcba" jÃ¡ foi lido.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'Cadeia + Retornos KMP', dialog: [
        'q0â€”dâ†’q1â€”câ†’q2â€”bâ†’q3â€”aâ†’q4(f). Cadeia principal do sufixo.',
        'q0 loop a,b,c (prefixo descartado). q1 loop d (novo "d" reinicia a busca).',
        'Mismatches em q2,q3,q4 voltam para q0 ou q1 â€” nunca desperdiÃ§am um "d".',
      ] },
    },
    boardWords: ['dcba', 'adcba', 'aadcba'],
    guidedLesson: [
      { text: 'Sufixo obrigatÃ³rio "dcba"!<br/>Aceitar: <b>dcba</b>, <b>adcba</b>, <b>aadcba</b>. Rejeitar: Î», dcb, abcd.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>dcba</b>: cadeia exata q0â†’q1(d)â†’q2(c)â†’q3(b)â†’q4(a,final).',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1(d)â†’q2(c)â†’q3(b)â†’q4(final,a). "dcba"âœ“. PrÃ³ximas: "adcba" e "aadcba"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 30, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 70, y: 50, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 90, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'd' },
            { from: 'q1', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q4', symbol: 'a' },
          ] } },
      { text: 'Foco em <b>adcba</b> e <b>aadcba</b>: q0 lÃª "a" â€” sem seta! Preciso de loops e retornos KMP.',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 30, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 70, y: 50, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 90, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'd' },
            { from: 'q1', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q4', symbol: 'a' },
          ] } },
      { text: 'Fix KMP: q0 loop a,b,c; q1 loop d; mismatchesâ†’q0/q1. "adcba"âœ“, "aadcba"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3,
        stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 30, y: 50, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 50, y: 50, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 70, y: 50, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 90, y: 50, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'a,b,c' },
            { from: 'q0', to: 'q1', symbol: 'd' },
            { from: 'q1', to: 'q0', symbol: 'a,b' },
            { from: 'q1', to: 'q1', symbol: 'd' },
            { from: 'q1', to: 'q2', symbol: 'c' },
            { from: 'q2', to: 'q0', symbol: 'a,c' },
            { from: 'q2', to: 'q1', symbol: 'd' },
            { from: 'q2', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q0', symbol: 'b,c' },
            { from: 'q3', to: 'q1', symbol: 'd' },
            { from: 'q3', to: 'q4', symbol: 'a' },
            { from: 'q4', to: 'q0', symbol: 'a,b,c' },
            { from: 'q4', to: 'q1', symbol: 'd' },
          ],
        } },
    ] },
  { id: 38, label: "L37", formula: "L = { w âˆˆ {a,b,c,d}* | tem abcd ou dcba como subpalavra }",        desc: "",                                                                 shortestWord: "abcd",     regex: /^[abcd]*(abcd|dcba)[abcd]*$/,                               alphabet: ['a', 'b', 'c', 'd'],   acceptedWords: ["abcd","dcba","aabcdb"],  rejectedWords: ["Î»","abc","dcb"],       hint: "Dois caminhos independentes saindo do inÃ­cio que caem num mesmo estado de vitÃ³ria.",                                successMsg: "BifurcaÃ§Ã£o de subpalavras dominada!",
    tutorials: {
      onStart: { type: 'theory', title: 'Subpalavra: "abcd" ou "dcba"!', dialog: [
        'L37: basta conter "abcd" ou "dcba" em qualquer posiÃ§Ã£o da palavra.',
        '"abcd" âœ“, "dcba" âœ“, "aabcdb" âœ“ (contÃ©m "abcd"). "abc", "dcb" âœ— (incompletos).',
        'Dois caminhos independentes do q0 convergem para o mesmo estado final q4.',
      ] },
      onDrawGraph: { type: 'mechanic', title: 'BifurcaÃ§Ã£o de Dois Caminhos', dialog: [
        'Caminho 1 (topo): q0â€”aâ†’q1â€”bâ†’q2â€”câ†’q3â€”dâ†’q4(f). "abcd" aceito!',
        'Caminho 2 (base): q0â€”dâ†’q5â€”câ†’q6â€”bâ†’q7â€”aâ†’q4(f). "dcba" aceito!',
        'q4 loop em tudo. KMP garante que mismatches reiniciam corretamente nos dois caminhos.',
      ] },
    },
    boardWords: ['abcd', 'dcba', 'aabcdb'],
    guidedLesson: [
      { text: 'Subpalavra "abcd" ou "dcba"!<br/>Aceitar: <b>abcd</b>, <b>dcba</b>, <b>aabcdb</b>. Rejeitar: Î», abc, dcb.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>abcd</b> e <b>dcba</b>: dois caminhos opostos â€” q0â†’{q1-q4} e q0â†’{q5-q4}.',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: caminho abcd (topo) e dcba (base) convergem em q4(final). "abcd"âœ“, "dcba"âœ“. PrÃ³xima: "aabcdb"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 30, y: 20, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 55, y: 20, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 75, y: 20, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 92, y: 50, isInitial: false, isFinal: true  },
            { id: 'q5', label: 'q5', x: 30, y: 80, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 55, y: 80, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 75, y: 80, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
            { from: 'q0', to: 'q5', symbol: 'd' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q7', symbol: 'b' },
            { from: 'q7', to: 'q4', symbol: 'a' },
          ] } },
      { text: 'Foco em <b>aabcdb</b>: q1 lÃª 2Â° "a" â€” sem seta! Preciso de loops e retornos KMP.',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 30, y: 20, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 55, y: 20, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 75, y: 20, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 92, y: 50, isInitial: false, isFinal: true  },
            { id: 'q5', label: 'q5', x: 30, y: 80, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 55, y: 80, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 75, y: 80, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
            { from: 'q0', to: 'q5', symbol: 'd' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q6', to: 'q7', symbol: 'b' },
            { from: 'q7', to: 'q4', symbol: 'a' },
          ] } },
      { text: 'Fix KMP: q4 loop {a,b,c,d}, loops em q0, retornos parciais. "aabcdb"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3,
        stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 10, y: 50, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 30, y: 20, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 55, y: 20, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 75, y: 20, isInitial: false, isFinal: false },
            { id: 'q4', label: 'q4', x: 92, y: 50, isInitial: false, isFinal: true  },
            { id: 'q5', label: 'q5', x: 30, y: 80, isInitial: false, isFinal: false },
            { id: 'q6', label: 'q6', x: 55, y: 80, isInitial: false, isFinal: false },
            { id: 'q7', label: 'q7', x: 75, y: 80, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q0', symbol: 'b,c' },
            { from: 'q0', to: 'q1', symbol: 'a' },
            { from: 'q0', to: 'q5', symbol: 'd' },
            { from: 'q1', to: 'q1', symbol: 'a' },
            { from: 'q1', to: 'q2', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'c' },
            { from: 'q1', to: 'q5', symbol: 'd' },
            { from: 'q2', to: 'q1', symbol: 'a' },
            { from: 'q2', to: 'q0', symbol: 'b' },
            { from: 'q2', to: 'q3', symbol: 'c' },
            { from: 'q2', to: 'q5', symbol: 'd' },
            { from: 'q3', to: 'q1', symbol: 'a' },
            { from: 'q3', to: 'q0', symbol: 'b,c' },
            { from: 'q3', to: 'q4', symbol: 'd' },
            { from: 'q4', to: 'q4', symbol: 'a,b,c,d' },
            { from: 'q5', to: 'q1', symbol: 'a' },
            { from: 'q5', to: 'q0', symbol: 'b' },
            { from: 'q5', to: 'q6', symbol: 'c' },
            { from: 'q5', to: 'q5', symbol: 'd' },
            { from: 'q6', to: 'q1', symbol: 'a' },
            { from: 'q6', to: 'q7', symbol: 'b' },
            { from: 'q6', to: 'q0', symbol: 'c' },
            { from: 'q6', to: 'q5', symbol: 'd' },
            { from: 'q7', to: 'q4', symbol: 'a' },
            { from: 'q7', to: 'q0', symbol: 'b,c' },
            { from: 'q7', to: 'q5', symbol: 'd' },
          ],
        } },
    ] },
  { id: 39, label: "L38", formula: "L = { (a+b)* | qtd de 'a' Ã© par, qtd de 'b' Ã© Ã­mpar }",            desc: "",                                                                 shortestWord: "b",        regex: /^.*$/, validate: w => [...w].filter(c=>c==='a').length%2===0 && [...w].filter(c=>c==='b').length%2===1, alphabet: ['a', 'b'],             acceptedWords: ["b","aab","bbb"],          rejectedWords: ["Î»","a","ab"],          hint: "VocÃª precisa de 4 estados para controlar: Par/Par, Par/Ãmpar, Ãmpar/Par, Ãmpar/Ãmpar.",                             successMsg: "Quadrante de paridade solucionado.",
    tutorials: {
      onStart: { type: 'theory', title: 'Paridade Dupla: a-par e b-Ã­mpar!', dialog: [
        'L38: contar a\'s e b\'s separadamente. Aceito quando #a par E #b Ã­mpar.',
        '"b" âœ“ (0a=par, 1b=Ã­mpar). "aab" âœ“ (2a=par, 1b=Ã­mpar). "ab" âœ— (1a=Ã­mpar, 1b=Ã­mpar).',
        '4 combinaÃ§Ãµes de paridade â†’ 4 estados: (p,p)=q0, (p,Ã­)=q1, (Ã­,p)=q2, (Ã­,Ã­)=q3.',
        'Cada \'a\' lido troca a paridade de a. Cada \'b\' lido troca a paridade de b.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '4 Estados em Quadrado', dialog: [
        'q0(ini)=(p,p), q1(f)=(p,Ã­), q2=(Ã­,p), q3=(Ã­,Ã­). SÃ³ q1 Ã© final.',
        'Ler \'b\': q0â†”q1 e q2â†”q3 (troca bit-b). Ler \'a\': q0â†”q2 e q1â†”q3 (troca bit-a).',
        '"aab": q0â€”aâ†’q2â€”aâ†’q0â€”bâ†’q1(f) âœ“. "ab": q0â€”aâ†’q2â€”bâ†’q3 (nÃ£o-final) âœ—.',
      ] },
    },
    boardWords: ['b', 'bbb', 'aab'],
    guidedLesson: [
      { text: 'Paridade dupla: #a par AND #b Ã­mpar!<br/>Aceitar: <b>b</b>, <b>bbb</b>, <b>aab</b>. Rejeitar: Î», a, ab.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>b</b> e <b>bbb</b>: raia do b â€” q0(ini)â†”q1(final) via b resolve as duas!',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q1(b,final)â†’q0(b). "b"=q0â†’q1âœ“, "bbb"=q0â†’q1â†’q0â†’q1âœ“. PrÃ³xima: "aab"!',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
          ] } },
      { text: 'Foco em <b>aab</b>: q0 lÃª "a" â€” sem seta! Preciso da raia do a (q2, q3).',
        boardDoneUpTo: 2, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 35, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
          ] } },
      { text: 'Solução: q0â†”q2(a), q1â†”q3(a), q2â†”q3(b). "aab"=q0â†’q2â†’q0â†’q1âœ“. "ab"â†’q3(nÃ£o-final)âœ—. ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 35, isInitial: false, isFinal: true  },
            { id: 'q2', label: 'q2', x: 25, y: 70, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 75, y: 70, isInitial: false, isFinal: false },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q0', symbol: 'a' },
            { from: 'q1', to: 'q3', symbol: 'a' },
            { from: 'q3', to: 'q1', symbol: 'a' },
            { from: 'q2', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q2', symbol: 'b' },
          ] } },
    ] },
  { id: 40, label: "L39", formula: "L = { (a+b)* | qtd de 'a' Ã© Ã­mpar, qtd de 'b' Ã© Ã­mpar }",          desc: "",                                                                 shortestWord: "ab",       regex: /^.*$/, validate: w => [...w].filter(c=>c==='a').length%2===1 && [...w].filter(c=>c==='b').length%2===1, alphabet: ['a', 'b'],             acceptedWords: ["ab","abbb","aaabbb"],     rejectedWords: ["Î»","a","b"],           hint: "Parecido com a anterior, mas o estado de aceitaÃ§Ã£o muda.",                                                          successMsg: "Paridade Ã­mpar cruzada!",
    tutorials: {
      onStart: { type: 'theory', title: 'Paridade Dupla: a-Ã­mpar e b-Ã­mpar!', dialog: [
        'L39: aceito quando #a Ã­mpar E #b Ã­mpar. Estado final: q3=(Ã­,Ã­) no canto oposto de q0.',
        '"ab" âœ“ (1a=Ã­mpar, 1b=Ã­mpar). "abbb" âœ“ (1a=Ã­mpar, 3b=Ã­mpar). "a" âœ— (1a=Ã­mpar, 0b=par).',
        '4 estados de paridade: q0=(p,p), q1=(p,Ã­), q2=(Ã­,p), q3=(Ã­,Ã­). SÃ³ q3 Ã© final.',
        'Mesmo quadrado da L38, mas o estado de aceitaÃ§Ã£o muda de q1 para q3.',
      ] },
      onDrawGraph: { type: 'mechanic', title: '4 Estados â€” Quadrante Oposto!', dialog: [
        'q0(ini)=(p,p), q1=(p,Ã­), q2=(Ã­,p), q3(f)=(Ã­,Ã­). SÃ³ q3 Ã© final.',
        'Ler \'a\': q0â†”q2 e q1â†”q3 (troca bit-a). Ler \'b\': q0â†”q1 e q2â†”q3 (troca bit-b).',
        '"ab": q0â€”aâ†’q2â€”bâ†’q3(f) âœ“. "aaabbb": 3a e 3b = Ã­mpar/Ã­mpar â†’ q3(f) âœ“.',
      ] },
    },
    boardWords: ['ab', 'abbb', 'aaabbb'],
    guidedLesson: [
      { text: 'Paridade dupla: #a Ã­mpar AND #b Ã­mpar!<br/>Aceitar: <b>ab</b>, <b>abbb</b>, <b>aaabbb</b>. Rejeitar: Î», a, b.',
        boardDoneUpTo: -1, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Foco em <b>ab</b>: 1a e 1b â€” q0â†’q2(a)â†’q3(b,final). Quadrado parcial!',
        boardDoneUpTo: 0, stateUpdate: { nodes: [], transitions: [] } },
      { text: 'Solução: q0â†’q2(a)â†’q3(final,b). "ab"=q0â†’q2â†’q3âœ“. PrÃ³ximas: "abbb" e "aaabbb"!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 25, y: 70, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 75, y: 70, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q3', symbol: 'b' },
          ] } },
      { text: 'Foco em <b>abbb</b> e <b>aaabbb</b>: precisam de todas as raias do quadrado!',
        boardDoneUpTo: 1, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 25, y: 70, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 75, y: 70, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q3', symbol: 'b' },
          ] } },
      { text: 'Solução: q0â†”q1(b), q2â†”q0(a), q1â†”q3(a), q2â†”q3(b). "abbb"âœ“, "aaabbb"âœ“ ConcluÃ­do!',
        boardDoneUpTo: 3, stateUpdate: {
          nodes: [
            { id: 'q0', label: 'q0', x: 25, y: 35, isInitial: true,  isFinal: false },
            { id: 'q1', label: 'q1', x: 75, y: 35, isInitial: false, isFinal: false },
            { id: 'q2', label: 'q2', x: 25, y: 70, isInitial: false, isFinal: false },
            { id: 'q3', label: 'q3', x: 75, y: 70, isInitial: false, isFinal: true  },
          ],
          transitions: [
            { from: 'q0', to: 'q1', symbol: 'b' },
            { from: 'q1', to: 'q0', symbol: 'b' },
            { from: 'q0', to: 'q2', symbol: 'a' },
            { from: 'q2', to: 'q0', symbol: 'a' },
            { from: 'q1', to: 'q3', symbol: 'a' },
            { from: 'q3', to: 'q1', symbol: 'a' },
            { from: 'q2', to: 'q3', symbol: 'b' },
            { from: 'q3', to: 'q2', symbol: 'b' },
          ] } },
    ] },
];
